### ISSUE TITLE
_ExtraSdkVersion causes build break in 15.2

### ISSUE THREAD

**Issue by AArnott** [onovotny/MSBuildSdkExtras#10]
Packing a project with Dev15.2 fails with this:

`msbuild /t:pack`

> C:\Users\andre\.nuget\packages\msbuild.sdk.extras\1.0.4\buildMultiTargeting\MSBuild.Sdk.Extras.targets(8,14): error MSB4086: A numeric comparison was attempted on "$(_ExtrasSdkVersion)" that evaluates to "" instead of a number, in condition "'$(IncludeBuildOutput)' == 'true' and '$(_ExtrasSdkVersion)' < 2.0". [E:\git\c5\C5\C5.csproj]

**Comment by AArnott** [comment]
v1.0.3 works fine. It breaks with v1.0.4

**Comment by onovotny** [comment]
Should be fixed now in the 1.0.5-beta on the CI feed, can you validate? Issue was that the property detection was only in the single TFM targets and not the mutitargeting one.

**Comment by onovotny** [comment]
Should be fixed in 1.0.5.

**Comment by AArnott** [comment]
Thanks. I was camping till a few hours ago so I couldn't get to this earlier to validate.

**Comment by onovotny** [comment]
np, please lmk if it's still not working for you
