### ISSUE TITLE
"win8" throws when building with 1.6.41 (1.5.4 works)

### ISSUE THREAD

**Issue by mattleibow** [onovotny/MSBuildSdkExtras#100]
When building, I get this error:

> C:\Program Files\dotnet\sdk\2.1.300\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(198,5): error : Assets file 'C:\Projects\Modernizing Projects Meetup\Demo.Win8\Demo.Win8\obj\project.assets.json' doesn't have a target for '.NETCore,Version=v4.5'. Ensure that restore has run and that you have included 'netcore45' in the TargetFrameworks for your project. [C:\Projects\Modernizing Projects Meetup\Demo.Win8\Demo.Win8\Demo.Win8.csproj]

[Demo.Win8.zip](https://github.com/onovotny/MSBuildSdkExtras/files/2226265/Demo.Win8.zip)

If I set the version down to 1.5.4, it builds just fine.

**Comment by onovotny** [comment]
Fixed in the latest release, thanks
