### ISSUE TITLE
Support for command line dotnet build or dotnet msbuild?

### ISSUE THREAD

**Issue by zlatanov** [onovotny/MSBuildSdkExtras#102]
If we create a WPF project with the new SDK style, everything works very well inside Visual Studio. But if we try to build the project from the command line, using the dotnet build/msbuild, it doesn't work.

What would it take to make this work? I am willing to help but I don't know if it is even possible.

And by the way, THANK YOU for this project, it is as awesome!

**Comment by onovotny** [comment]
You have to use `msbuild.exe`, which runs on the full framework. `dotnet build` runs on .NET Core, and most of the build tasks don't support that.
