### ISSUE TITLE
Wpf - Provide ThemeInfo attribute

### ISSUE THREAD

**Issue by kvpt** [onovotny/MSBuildSdkExtras#104]
Hi,

I migrated one wpf project to this library.
It worked well at first glance but I noticed a regression in rendering.
After some [search ](https://stackoverflow.com/a/9528032)I found that the issue was because the application used the theme functionality which depend on an attribute defined by default in the AssemblyInfo.cs.

```csharp 
[assembly: ThemeInfo(ResourceDictionaryLocation.None, ResourceDictionaryLocation.SourceAssembly)]
```

When migrating the project I deleted the file AssemblyInfo.cs which also removed the ThemeInfo attribute.

Considering that this attribute is provided by default when creating a wpf project, I think that this attribute need to be provided when using ExtrasEnableWpfProjectSetup to not cause a regression like this.

What do you think about it ?

**Comment by onovotny** [comment]
I'm not sure this is a good candidate for the extras as the parameter can vary by the project. Not all of the information in AssemblyInfo.cs can be inferred. I would suggest either deleting just the attributes that are defaulted and leaving that, or putting that in another file.
