### ISSUE TITLE
MSB3052: The parameter to the compiler is invalid

### ISSUE THREAD

**Issue by amis92** [onovotny/MSBuildSdkExtras#106]
I'm targeting:
* `portable-net40+win8+wpa81` (Profile92)
* `portable-net45+win8+wpa81+wp8` (Profile259)

I'm getting that warning (for both, with appropriate defines):

>MSB3052 The parameter to the compiler is invalid, '/define:PORTABLE_NET40+WIN8+WPA81' will be ignored. CodeGeneration.Roslyn.Attributes C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Roslyn\Microsoft.CSharp.Core.targets	52		

It seems the parameter includes `+` signs which aren't valid.

**Comment by sergtk** [comment]
If configuration startes with number (which is allowed) then it produces define which starts with number. But such define is not allowed. Can this be fixed?
Thanks
