### ISSUE TITLE
WPF: Building on a build server using 'dotnet'

### ISSUE THREAD

**Issue by alexdegroot** [onovotny/MSBuildSdkExtras#107]
I'm trying to get it working on a build server.
My files look like this:
Global.json:
`{
    "msbuild-sdks": {
        "MSBuild.Sdk.Extras": "1.6.47"
    }
}`
Project file:

```
<Project Sdk="MSBuild.Sdk.Extras">
  <PropertyGroup>
    <TargetFrameworks>net461</TargetFrameworks>
    <ExtrasEnableWpfProjectSetup>true</ExtrasEnableWpfProjectSetup>
    <RuntimeIdentifiers>win</RuntimeIdentifiers>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="PresentationCore" />
    <Reference Include="PresentationFramework" />
    <Reference Include="System.Windows" />
    <Reference Include="System.Xaml" />
    <Reference Include="WindowsBase" />
  </ItemGroup>
</Project>
```

When I run from Visual Studio or from Rider, the Xaml-files compile without any issues. Unfortunately when I run from the command line (dotnet build / dotnet msbuild) I get errors like this:
`ExampleUserControl.xaml.cs(10,13): error CS0103: The name 'InitializeComponent' does not exist in the current context [Example.Instructor.Wpf.csproj]
ExampleFailures.xaml.cs(7,13): error CS0103: The name 'InitializeComponent' does not exist in the current context [Example.Instructor.Wpf.csproj]`

When I run it through MSBuild I get it working again:
`"C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe" .\Extensions.Example.sln /v:q /t:build /restore`

Is there a way to use 'dotnet build/msbuild'? Thanks!

**Comment by onovotny** [comment]
You cannot use `dotnet build` since those run on the .NET Core runtime. The targets needed for WPF only work on the full .NET Framework, which is why you need to use `msbuild.exe`.

**Comment by alexdegroot** [comment]
Wow, Formula 1 response... :) Thanks @onovotny! Might be good to add to the Readme.
