### ISSUE TITLE
reference assembly is not build/renamed/copied for winmd projects

### ISSUE THREAD

**Issue by attilah** [onovotny/MSBuildSdkExtras#109]
Scenario UAP app consumes Windows Component library which is build for AnyCPU.

Project targets:
- UAP Application (x86, x64, ARM)
- Windows Component Library (AnyCPU)

Expected result:
- Application compiles and consumes the ref assembly

Current result:
- Application fails to compile, because ref assembly is not copied to ref dir for the component library. Ref directory is created, but no copy happens, obj dir has the winmdobj file.

Another thing I see is that Deploy is not available as an option for some reason, not sure what triggers it in VS.

In the application directory I kept the original csproj which just works.

Repro: https://t.co/9Z8LXhaKQY

**Comment by onovotny** [comment]
Closing as per #113. Only class libraries are supported for UWP.
