### ISSUE TITLE
Problem with NuGet support

### ISSUE THREAD

**Issue by ticotaco72** [onovotny/MSBuildSdkExtras#110]
Compile error:
NETSDK1005 Resource file "C: \ Users \ User \ Desktop \ osu developing \ osu-framework \ osu.Framework \ obj \ project.assets.json" has no target for "MonoAndroid, Version = v8.1". Ensure that the restore is running and that the item "monoandroid81" is included in the TargetFrameworks element for the project. osu.Framework C: \ Program Files \ dotnet \ sdk \ 2.1.401 \ Sdks \ Microsoft.NET.Sdk \ targets \ Microsoft.PackageDependencyResolution.targets 198

What's wrong?

MSBuildSdkExtras version: 1.6.47
VS community: 15.8.2

**Comment by ticotaco72** [comment]
and win 10 ver 1803

**Comment by onovotny** [comment]
how are you trying to build the project? you need to use msbuild.exe not dotnet build.

**Comment by ticotaco72** [comment]
How to check it and change? I don't see an option for this.

**Comment by onovotny** [comment]
Are you building it in Visual Studio or the command line?

**Comment by ticotaco72** [comment]
In vs

**Comment by ticotaco72** [comment]
But maybe some config cause I'm not the only one to work on this project

**Comment by onovotny** [comment]
If this is still happening, I'd suggest verifying that "Restore NuGet Packages automatically" is enabled in the VS preferences for NuGet. If that doesn't solve it, I'd use the "report a problem" button on the top-right of VS.

Doesn't seem like an issue with these SDK's, so I'm closing here for now.
