### ISSUE TITLE
Can't install nuget package

### ISSUE THREAD

**Issue by ticotaco72** [onovotny/MSBuildSdkExtras#111]
error:
The "MSBuild.Sdk.Extras 1.6.41" package has the "MSBuildSdk" package type, which is not supported by the "osu.Framework" project.

All versions above 1.5.4 gives this error when installing with package manager. But when i hardcoded it to csproj and global.json then all worked properly.

VS community: 15.8.2
Win 10 ver 1803

**Comment by MSiccDev** [comment]
Same here, need to manually update global.json AND all project files...

**Comment by onovotny** [comment]
Not sure why that particular error is happening, but it is the better to use the `Sdk` attribute with the `global.json` to control the verison. Unfortunately, NuGet doesn't support that yet.

**Comment by IDEASDOT** [comment]
same issue
