### ISSUE TITLE
UAP test projects have no deploy option available

### ISSUE THREAD

**Issue by attilah** [onovotny/MSBuildSdkExtras#113]
The issue is that UAP application and test projects (both are appcontainers) are not working correctly with Extras.

The root cause is that for some reason VS is not detecting the project as "Deployable", hence no target device can be determined for deployment (LocalMachine by default), and this makes it unit test running fail. If the app is a regular app, then it cannot run, since deployment is mandatory for UAPs.

I've created a repro project, one is using the old style csproj, the other is using Extras:

https://github.com/attilah/uaprepro

The other problem is is native toolchain is enabled (like it is enabled for UAP projects), then another error happens:

https://github.com/attilah/uaprepro/blob/master/UnitTestExtra/UnitTestExtra.csproj#L12

**Comment by onovotny** [comment]
UWP is only supported for class libraries. Some project types, like UWP, Xamarin, and ASPNet 4.x require project system support.
