### ISSUE TITLE
WCF Connected Service Reference Support

### ISSUE THREAD

**Issue by MeikTranel** [onovotny/MSBuildSdkExtras#121]
Sdk-based csprojs need glue-props to support Full Framework WCF Service Designers.
Migrating existing WCF References already produces compilable Projects that work, but the SDK-based CSProj currently only supports adding new .NET Core WCF Services with dotnet-svcutil. Updating existing full framework WSDLs does not because the Designer doesn't know where to look for the SVCMap etc.

**Comment by onovotny** [comment]
For designer support, I'd suggest filing a suggestion here: https://developercommunity.visualstudio.com/spaces/8/index.html

There's not likely much the Extras can do if the underlying support isn't present.
