### ISSUE TITLE
Targeting Packs, TFMs...

### ISSUE THREAD

**Issue by DylanFPS** [onovotny/MSBuildSdkExtras#123]
Hi. I'm looking to reference some Xamarin TFMs from my library, but Rider and Visual Studio both complain about a missing targeting pack.
![image](https://user-images.githubusercontent.com/11160611/46246503-bde3e380-c3f6-11e8-91c8-0b652a48b0ca.png)
![image](https://user-images.githubusercontent.com/11160611/46246544-845fa800-c3f7-11e8-9cd6-b564e7639537.png)
![image](https://user-images.githubusercontent.com/11160611/46246547-8d507980-c3f7-11e8-9734-994884e02cec.png)

My ReferenceAssemblies dir only contains Xamarin.iOS v1.0 and Xamarin.Mac v2.0, i'm unsure on where to get later versions.

**Comment by onovotny** [comment]
I can't help with Rider, but for Visual Studio, you need to ensure you have the Xamarin workload installed. You can run the Visual Studio Installer and select "Modify" to add/change your installed workloads.

**Comment by DylanFPS** [comment]
The Xamarin Workload is installed, and also Rider looks in Visual Studio's directories so what's VS' is Rider's.

**Comment by onovotny** [comment]
The TFM for Xamarin.iOS is `XamarinIos10`; and for mac it's `XamarinMac20`. They do not follow the OS versions. If you fix the version numbers, it should work for you.

**Comment by DylanFPS** [comment]
I don’t think there are compile time constants for them, as they’re not
Framework-level components.
