### ISSUE TITLE
Item templates are missing in WPF project

### ISSUE THREAD

**Issue by thomaslevesque** [onovotny/MSBuildSdkExtras#126]
I have a WPF project using MSBuildSdkExtras:

```xml
<Project Sdk="MSBuild.Sdk.Extras/1.6.55">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net461</TargetFramework>
        <ExtrasEnableWpfProjectSetup>true</ExtrasEnableWpfProjectSetup>
        <PlatformTarget>AnyCPU</PlatformTarget>
        <DebugType>embedded</DebugType>
        <DebugSymbols>true</DebugSymbols>
        <AutoGenerateBindingRedirects>false</AutoGenerateBindingRedirects>
        <ApplicationIcon>Resources\app.ico</ApplicationIcon>
    </PropertyGroup>

</Project>
```

When I use the "Add > New item" command in Visual Studio, most of the WPF item templates are missing:

![image](https://user-images.githubusercontent.com/1864281/47727949-ae59f380-dc5d-11e8-9aba-3fa0811af546.png)

Could this be caused by MSBuildSdkExtras? Is there a way to fix it?

I tried copying the `ProjectTypeGuids` from a classic WPF project (in which templates work fine), but it seems to have no effect.

**Comment by onovotny** [comment]
I'm not sure there's an easy fix for this, but open to suggestions if someone finds a way.

**Comment by thomaslevesque** [comment]
I guess that to fix this, we'd need to know how VS decides which templates to show for a given project. I don't know if there's any public information on this.

**Comment by onovotny** [comment]
Closing as out of scope for these extras. Templates will come from .NET Core 3/VS 2019
