### ISSUE TITLE
Support for .NET Core app 3.0

### ISSUE THREAD

**Issue by GeertvanHorrik** [onovotny/MSBuildSdkExtras#131]
We are using this (happily!) for all our projects, and want to investigate whether we can add support for .NET Core 3.0 for WPF in all our libraries.

I am now getting this error:

```
C:\Program Files\dotnet\sdk\2.1.500\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(137,5): error NETSDK1045: The current .NET SDK does not support targeting .NET Core 3.0.  Either target .NET Core 2.1 or lower, or use a version of the .NET SDK that supports .NET Core 3.0. [C:\Source\Orc.FilterBuilder\src\Orc.FilterBuilder\Orc.FilterBuilder.csproj]
```

I am coming from 1.5.4, so made 2 changes:

1) Update to `Project Sdk="MSBuild.Sdk.Extras"` instead of referencing it as package reference
2) Add netcoreapp3.0 as target framework

Will keep posting investigations here, it might be of use for others.

**Comment by onovotny** [comment]
For WPF, you don't need the extras at all anymore. The recommended approach would be to use the new `Microsoft.NET.Sdk.WindowsDesktop` SDK.

The extras will likely be relevant for Xamarin and UWP.

**Comment by onovotny** [comment]
The end goal is to allow the extras to co-exist, but the WPF-related functionality will call in the desktop one where available. Just hasn't been updated to co-exist yet.

**Comment by onovotny** [comment]
Done in #133
