### ISSUE TITLE
Shouldn't ExtrasUseWindowsDesktopApp only be enabled for netcoreapp?

### ISSUE THREAD

**Issue by GeertvanHorrik** [onovotny/MSBuildSdkExtras#134]
https://github.com/onovotny/MSBuildSdkExtras/blob/e5a8b39d1572a12329ccfaaa3e5f225e5b0523af/Source/MSBuild.Sdk.Extras/Build/ExtrasShim.targets#L29

Currently testing out the latest bits. Shouldn't this only be enabled if the targetframework is a netcoreapp (so don't include in case of net46, etc)?

**Comment by onovotny** [comment]
No since the Desktop SDK includes both netcoreapp3.0 and net targets.
