### ISSUE TITLE
FSharp portable language target is not located in same place as CSharp and VisualBasic

### ISSUE THREAD

**Issue by jbtule** [onovotny/MSBuildSdkExtras#14]
Because of this, when compiling portable, will get error: 

> MSBuildSdkExtras.Common.targets(118,5): error : The specified TFM 'portable-net45+sl5+win8' is not valid. Check that it's a valid combination: http://portablelibraryprofiles.apps.stephencleary.com/

_Actual FSharp location:_
`<LanguageTargets>$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\FSharp\Microsoft.Portable.FSharp.Targets</LanguageTargets>`

**Comment by jbtule** [comment]
Example: https://github.com/fsprojects/FSharp.Interop.Dynamic/commits/vs2017-fsproj

**Comment by onovotny** [comment]
@jbtule can you please try the latest off of the CI feed? Should be `1.0.6-beta.*` I just fixed this but would like your confirmation before I push it to NuGet.org.

**Comment by jbtule** [comment]
Well it worked on windows!  

https://ci.appveyor.com/project/jbtule/fsharp-dynamic-832/build/73

On mac, it's looking for .mdb files all of a sudden.

https://travis-ci.org/fsprojects/FSharp.Interop.Dynamic/builds/255652802?utm_source=github_status&utm_medium=notification

> /usr/local/share/dotnet/sdk/1.0.4/Sdks/NuGet.Build.Tasks.Pack/buildCrossTargeting/NuGet.Build.Tasks.Pack.targets(104,5): error MSB4018: The "PackTask" task failed unexpectedly. [/Users/travis/build/fsprojects/FSharp.Interop.Dynamic/FSharp.Interop.Dynamic/FSharp.Interop.Dynamic.fsproj]
> /usr/local/share/dotnet/sdk/1.0.4/Sdks/NuGet.Build.Tasks.Pack/buildCrossTargeting/NuGet.Build.Tasks.Pack.targets(104,5): error MSB4018: System.IO.FileNotFoundException: File not found: '/Users/travis/build/fsprojects/FSharp.Interop.Dynamic/FSharp.Interop.Dynamic/obj/Release/portable-net45+sl5+win8/FSharp.Interop.Dynamic.dll.mdb'.

**Comment by onovotny** [comment]
I'm not sure where that error lives... might be worth an issue on the NuGet repo if it's with the Pack targets. I'd split this into two parts:

1. Building
2. Packing

Seems like 1 is working, but 2 is with the NuGet team.

**Comment by jbtule** [comment]
Yeah apparently msbuild has a hack on mono that allows the debugging extension to be changed to mdb which they use in a patched into the fsharp.language.targets on mono. 
https://github.com/mono/mono/blob/master/packaging/MacSDK/patches/fsharp-fix-mdb-support.patch

However nothing i'm building has is outputting mdbs. So I have a work around for my purposes,  I set the `FscDebugFileExt`.
```
<PropertyGroup>
    <FscDebugFileExt>.pdb</FscDebugFileExt>
</PropertyGroup>
```
Seems appropriate and working.

**Comment by onovotny** [comment]
I just pushed 1.0.6 to NuGet.org, please lmk if you hit any other issues; happy to fix!
