### ISSUE TITLE
Reference assemblies ignored by projects using package.config 

### ISSUE THREAD

**Issue by bgavrilMS** [onovotny/MSBuildSdkExtras#141]
1. Create a project that uses the "old" packages.config style, for example a xamarin ios project (not xforms)
2. Take a dependency on a nuget package that uses ref assemblies, for example https://www.nuget.org/packages/Microsoft.Identity.Client/
3. Ctrl-Click into a type from this package to see the path to the actual DLL 

Actual:
packages\Microsoft.Identity.Client.2.6.1\ **lib** \xamarinios10\Microsoft.Identity.Client.dll

Expected: 
packages\Microsoft.Identity.Client.2.6.1\ **ref** \xamarinios10\Microsoft.Identity.Client.dll

Note: Projects that use PackageReference are not affected by this problem. We have tested with netcore, netstandard, net desktop, xamarin ios, xamarin android and UWP.

Given that Visual Studio is trying to migrate people away from packages.config, this is probably not a high priority issue, but logging it for further references.

**Comment by onovotny** [comment]
Packages.config is not supported with ref assemblies at all. That requires either project.json or PackageReference.

**Comment by bgavrilMS** [comment]
@onovotny - we expose a lot more surface area in the libs and hide it in the refs. 

The user impact is that they will be able to code smth like _AcquireTokenByWindowsIntegratedAuth_ on iOS, in which case they will get a nice PlatformNotSupportedException at runtime. This is ok, but the ideal experience is to hide it altogether.

**Comment by onovotny** [comment]
I think in that case, you're doing the right thing, and the best you can do -- users need to move off of packages.config for the best experience all around.

**Comment by bgavrilMS** [comment]
Agreed, feel free to close this bug as "won't fix"
