### ISSUE TITLE
Cant find GetAssemblyAttribute target (v1.6.61)

### ISSUE THREAD

**Issue by robsonj** [onovotny/MSBuildSdkExtras#142]
I'm sure its something missing in our WPF project, but we're seeing the following error...

The target "GetAssemblyAttributes" does not exist in the project _PROJECTNAMEHERE_ _PATH_\.nuget\packages\msbuild.sdk.extras\1.6.61\Build\ReferenceAssembly.targets

Any idea on what we need to do to resolve this issue?

Thank you,
Jonathan

**Comment by onovotny** [comment]
Do you have the .NET Core SDK installed, and if so, what version? (you should be able to run `dotnet --info` from your solution directory to find out).

**Comment by robsonj** [comment]
Yep, I came to the same conclusion. One of our devs has an old version of VS2017, thus also an old SDK. I’m updating his install now which should also get him the newer SDK.

Will close if that solves it - most likely

**Comment by robsonj** [comment]
Resolved. Was due to having an old SDK

**Comment by robsonj** [comment]
Thank you for the quick response btw @onovotny !
