### ISSUE TITLE
UWP Reference 6.2.2, but doesn't exist.... 

### ISSUE THREAD

**Issue by jamesmontemagno** [onovotny/MSBuildSdkExtras#143]
For the main UWP reference.... this version isn't out yet...

**Comment by onovotny** [comment]
Hmm...it is out, but they seem to have unlisted it. The meta-package version can always be overridden with the `ExtrasUwpMetaPackageVersion` property. I'll prob wait until Jan before updating this.

**Comment by jamesmontemagno** [comment]
Oh nice, didn't know that existed. If I used the newer 6.2.2 then I got an exception with Async stuff :( <3 happy holiday's buddy <3

**Comment by onovotny** [comment]
What exception were you seeing? It should be working...?

**Comment by jamesmontemagno** [comment]
So I have to assume it is because the test app couldn't install 6.2.2 and the library had 6.2.2:
Exception was: Could not load IAsyncStateMachine from system.runtime

**Comment by onovotny** [comment]
No....that’s something much worse. Emailing.
