### ISSUE TITLE
Error message when adding references in VS2017 UI

### ISSUE THREAD

**Issue by BrianDT** [onovotny/MSBuildSdkExtras#144]
Adding project references in the project file is fine but trying to add them in the VS 2017 UI generates an error. Right click on Dependencies and select ‘Add Reference …’ and the error ‘Missing value for TargetPlatformMDLocation property’ is displayed.
![error message capture](https://user-images.githubusercontent.com/4189260/50440514-7f26d200-08ee-11e9-8bb5-f2b7ce15bee3.PNG)

**Comment by BrianDT** [comment]
Should have said its a simple uap10.0 sample project
<Project Sdk="MSBuild.Sdk.Extras/1.6.65">

  <PropertyGroup>
    <TargetFramework>uap10.0</TargetFramework>
    <TargetPlatformVersion>10.0.17134.0</TargetPlatformVersion>
    <TargetPlatformMinVersion>10.0.16299.0</TargetPlatformMinVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SdkP1.UWP\SdkP1.UWP.csproj" />
  </ItemGroup>

</Project>

**Comment by onovotny** [comment]
Unfortunately, this is a bug in the VS tooling. It cannot add a reference to a multi-targeted project in the UI. As a workaround, you can add it manually in the project file as XML using the `ProjectReference` item.

@ridomin

**Comment by BrianDT** [comment]
Hi Oren, 

Would you mind clarifying a bit, because I feel that there must be more than just multi-targeting that is causing the issue.

If I have a project like 

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;netstandard1.4;net462</TargetFrameworks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SdkP3.DNSTD\SdkP3.DNSTD.csproj" />
  </ItemGroup>

</Project>

This has no problem adding the project reference in the UI.

Or am I misinterpreting what is implied by ‘multi-targeted’?

Thanks
Brian


Sent from Mail for Windows 10

**Comment by jimpierson** [comment]
@BrianDT 

I haven't fully tested whether this screws things up later down the line.... but I added the following 'Directory.Build.Props' to my local copy of Prism in the 'Windows10' folder. I have several extensions I've written and the above bugged the hell out of me!!!! Add Reference now works and everything 'appears' to compile correctly.... :)

`<Project>
	<Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />
	<PropertyGroup>
		<TargetPlatformWinMDLocation>C:\Program Files (x86)\Windows Kits\10\UnionMetadata</TargetPlatformWinMDLocation>
	</PropertyGroup>
</Project>`

**Comment by BrianDT** [comment]
The suggestion to define the WinMDLocation is a good one. Doesn’t look like it will work as defined above in a MSBuild.Sdk.Extras style project, but there is no problem adding the line-
<TargetPlatformWinMDLocation>C:\Program Files (x86)\Windows Kits\10\UnionMetadata</TargetPlatformWinMDLocation>
Directly into the project file, and this does resolve the issue.
Wonder why this was not done automatically when defining the target framework as uap10.0
