### ISSUE TITLE
Using preview 2.0.0 with VS 2017 (non-preview)

### ISSUE THREAD

**Issue by GeertvanHorrik** [onovotny/MSBuildSdkExtras#145]
When using VS 2017 preview, I get some binding redirect issues which are seemingly being caused by the new .NET Core 3.0 (preview) targets.

Therefore I wanted to use the stable version and check if that one works, but now I get these errors:

```
Project file must include the .NET Framework assembly 'WindowsBase, PresentationFramework' in the reference list
```

For my understanding, targeting net462 with `<UseWpf>true</UseWpf>` should add the references to Presentation*, right, even on the .net core 2.x sdks?

**Comment by onovotny** [comment]
I'm not sure I'm following what combination you're trying to use? You're looking to use the 2.0.0-preview.14 with what SDK?

**Comment by onovotny** [comment]
To be honest, while it should work, it hasn't been tested in that configuration. I'd recommend sticking with the 1.x Extras with the 2.0 SDK's.

That said, you can use the 3.0 preview SDK with VS 2017 (for Preview 1 anyway), by using a global.json: https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/master/global.json

Later .NET Core 3 previews will need VS 2019.

**Comment by GeertvanHorrik** [comment]
Correct, we are using VS 2017 (preview) / VS 2019 (preview) with the .NET Core 3.0 sdk (preview). However, looks like it has some binding redirect issues (e.g. https://github.com/Microsoft/msbuild/issues/4002).

We do use global.json, so I will revert there for now.
