### ISSUE TITLE
[2.0.0-preview.14] Issues building multi-targeting libs (UWP & NETCORE)

### ISSUE THREAD

**Issue by GeertvanHorrik** [onovotny/MSBuildSdkExtras#147]
To start with, version 2.0.0-preview.7 works fine. After an update to .14, it starts throwing errors:

```
AppDomain.cs(21,27): error CS0234: The type or namespace name 'ApplicationModel' does not exist in the namespace 'Windows' (are you missing an assembly reference?) [C:\Source\Catel\src\Catel.Core\Catel.Core.csproj]
AppDomain.cs(22,27): error CS0234: The type or namespace name 'Storage' does not exist in the namespace 'Windows' (are you missing an assembly reference?) [C:\Source\Catel\src\Catel.Core\Catel.Core.csproj] 
AppDomain.cs(148,63): error CS0234: The type or namespace name 'Storage' does not exist in the namespace 'Windows' (are you missing an assembly reference?) [C:\Source\Catel\src\Catel.Core\Catel.Core.csproj] Data\Interfaces\ISavableModel.cs(13,19): error CS0234: The type or namespace name 'Storage' does not exist in the namespace 'Windows' (are you missing an assembly reference?) [C:\Source\Catel\src\Catel.Core\Catel.Core.csproj]
Data\ModelBase.serialization.cs(20,19): error CS0234: The type or namespace name 'Storage' does not exist in the namespace 'Windows' (are you missing an
assembly reference?) [C:\Source\Catel\src\Catel.Core\Catel.Core.csproj]
Data\SavableModelBase.cs(18,19): error CS0234: The type or namespace name 'Storage' does not exist in the namespace 'Windows' (are you missing an assembly reference?) [C:\Source\Catel\src\Catel.Core\Catel.Core.csproj]
Services\LanguageService.xaml.cs(20,37): error CS0234: The type or namespace name 'ApplicationModel' does not exist in the namespace 'Windows' (are you missing an assembly reference?) [C:\Source\Catel\src\Catel.Core\Catel.Core.csproj]
Services\LanguageService.xaml.cs(21,19): error CS0234: The type or namespace name 'ApplicationModel' does not exist in the namespace 'Windows' (are you missing an assembly reference?) [C:\Source\Catel\src\Catel.Core\Catel.Core.csproj]
Services\LanguageService.xaml.cs(22,19): error CS0234: The type or namespace name 'Storage' does not exist in the namespace 'Windows' (are you missing an assembly reference?) [C:\Source\Catel\src\Catel.Core\Catel.Core.csproj]
Data\Interfaces\ISavableModel.cs(31,19): error CS0246: The type or namespace name 'IRandomAccessStream' could not be found (are you missing a using directive or an assembly reference?) [C:\Source\Catel\src\Catel.Core\Catel.Core.csproj]
Data\SavableModelBase.cs(81,26): error CS0246: The type or namespace name 'IRandomAccessStream' could not be found (are you missing a using directive or an assembly reference?) [C:\Source\Catel\src\Catel.Core\Catel.Core.csproj]
Data\SavableModelBase.cs(128,30): error CS0246: The type or namespace name 'IRandomAccessStream' could not be found (are you missing a using directive or an assembly reference?) [C:\Source\Catel\src\Catel.Core\Catel.Core.csproj]
IO\Path.cs(15,19): error CS0234: The type or namespace name 'Storage' does not exist in the namespace 'Windows' (are you missing an assembly reference?)
[C:\Source\Catel\src\Catel.Core\Catel.Core.csproj]
Configuration\ConfigurationService.cs(21,19): error CS0234: The type or namespace name 'Storage' does not exist in the namespace 'Windows' (are you missing an assembly reference?) [C:\Source\Catel\src\Catel.Core\Catel.Core.csproj]
Configuration\ConfigurationService.netfxcore.cs(13,19): error CS0234: The type or namespace name 'Storage' does not exist in the namespace 'Windows' (are you missing an assembly reference?) [C:\Source\Catel\src\Catel.Core\Catel.Core.csproj]
Configuration\ConfigurationService.netfxcore.cs(24,19): error CS0246: The type or namespace name 'ApplicationDataContainer' could not be found (are you missing a using directive or an assembly reference?) [C:\Source\Catel\src\Catel.Core\Catel.Core.csproj]
Configuration\ConfigurationService.netfxcore.cs(17,61): error CS0246: The type or namespace name 'ApplicationDataContainer' could not be found (are you missing a using directive or an assembly reference?) [C:\Source\Catel\src\Catel.Core\Catel.Core.csproj]
```

To repro:

1. Clone https://github.com/catel/catel (**release/5.9.0 branch**)
2. Go to the root, run `.\build.ps1 -target buildandpackagelocal` and verify it builds
3. Update to 2.0.0-preview.14 in /src/global.json
4. Go to the root, run `.\build.ps1 -target buildandpackagelocal` and verify it fails

**Comment by GeertvanHorrik** [comment]
TargetFrameworks: net45;net46;net47;netcoreapp3.0;uap10.0;netstandard2.0

Will check which one fails when i am at my desk

**Comment by onovotny** [comment]
@GeertvanHorrik any more details on this?

**Comment by GeertvanHorrik** [comment]
Sorry for my late reply, investigating now.

**Comment by GeertvanHorrik** [comment]
```
  <PropertyGroup>
    <TargetFrameworks>net45;net46;net47;netcoreapp3.0;uap10.0;netstandard2.0</TargetFrameworks>
    <AssemblyName>Catel.Core</AssemblyName>
    <RootNamespace>Catel</RootNamespace>
    <DefaultLanguage>en-US</DefaultLanguage>
    <PackageId>Catel.Core</PackageId>
    <PackageVersion>3.0.0-alpha0001</PackageVersion>
    <Description>Catel.Core library.</Description>
  </PropertyGroup>
```

I have nothing else explicitly specified.

**Comment by onovotny** [comment]
What Windows SDK's do you have installed?

Can you attach a binlog? (use the /bl parameter)

**Comment by GeertvanHorrik** [comment]
[MsBuild_Catel.Core.zip](https://github.com/onovotny/MSBuildSdkExtras/files/2851666/MsBuild_Catel.Core.zip)

**Comment by onovotny** [comment]
One thing immediately stands out -- you're using VS 2017 to build it. For .NET Core 3 targets, you need to use VS 2019's MSBuild. Does it still happen with that (and can you please provide a binlog in that config)?

**Comment by GeertvanHorrik** [comment]
A few things that happened:

1. I noticed it also exported the nuget api key, had to reset it...
2. I am using a preview version of .net core 3.0 that still supports VS 2017 (see https://github.com/dotnet/core/issues/2245)
3. Will try on vs 2019 right now

**Comment by onovotny** [comment]
Also, can you add `https://www.myget.org/F/msbuildsdkextras/api/v3/index.json` (the CI feed) to your nuget.config and try the .17 version? It may have a better error message.

**Comment by GeertvanHorrik** [comment]
When building with VS 2019 and the .17 version:

```
C:\Users\geert\.nuget\packages\msbuild.sdk.extras\2.0.0-preview.17\Build\Platforms\Windows.targets(76,5): error : Required Windows SDK Version 10.0.1
7763.0 is not installed. [C:\Source\catel\src\Catel.Core\Catel.Core.csproj]
```

**Comment by onovotny** [comment]
Do you indeed have the Windows SDK for 17763 installed? That would be the issue :)

**Comment by GeertvanHorrik** [comment]
I would like to believe so :)

![image](https://user-images.githubusercontent.com/1246444/52575365-5adf7000-2e1e-11e9-9495-1bb570f72e5e.png)

Let me double check everything.

**Comment by onovotny** [comment]
It's looking for this file: `$(MSBuildProgramFiles32)\Windows Kits\10\UnionMetadata\$(TargetPlatformVersion)\Windows.winmd`

**Comment by GeertvanHorrik** [comment]
I checked all installations (VS 2017, VS 2017 preview and VS 2019 preview), they all tell me I have it installed.

**Comment by GeertvanHorrik** [comment]
![image](https://user-images.githubusercontent.com/1246444/52575562-b4479f00-2e1e-11e9-8465-6f53ea3e965a.png)

**Comment by onovotny** [comment]
What's in the 10.0.17763.0 folder?

**Comment by GeertvanHorrik** [comment]
![image](https://user-images.githubusercontent.com/1246444/52575669-e22ce380-2e1e-11e9-914b-cd697545838e.png)

**Comment by onovotny** [comment]
weird, it's like the windows targets aren't being included/used....

https://github.com/onovotny/MSBuildSdkExtras/blob/9f5da180519ca9e84bc595e2b66889575e87b93b/Source/MSBuild.Sdk.Extras/Build/LanguageTargets/Windows.targets

Can you please attach an updated binlog?

**Comment by GeertvanHorrik** [comment]
BinLog generated with VS2019:

[MsBuild_Catel.Core.binlog.zip](https://github.com/onovotny/MSBuildSdkExtras/files/2851950/MsBuild_Catel.Core.binlog.zip)

**Comment by onovotny** [comment]
I think I see what the issue is, can you please try .18?

**Comment by GeertvanHorrik** [comment]
It's back at the errors I originally had:

[MsBuild_Catel.Core.binlog.zip](https://github.com/onovotny/MSBuildSdkExtras/files/2851988/MsBuild_Catel.Core.binlog.zip)

**Comment by GeertvanHorrik** [comment]
Note that this must have been introduced between .7 and .14. I tried comparing commits, but I have not fully into this project (source code) yet.

**Comment by onovotny** [comment]
The issue is that the LanguageTargets aren't being set correctly.

Do you have a file called Directory.build.shared.implicit.props? LanguageTargets are being set in that file, which prevents the correct things from happening in the SDK.

**Comment by onovotny** [comment]
This is causing your pain: https://github.com/Catel/Catel/blob/develop/src/Directory.build.shared.implicit.props#L51

**Comment by GeertvanHorrik** [comment]
Yeah, looks like removing that line solves the issue, thanks for helping out on that one. I will check if removing it has other implications, but that shouldn't be related to the sdk extras.

Thanks for all the help during this investigation. Again, if there is any way we can support you, let us know.

**Comment by SimonCropp** [comment]
i am getting the same error in https://github.com/CopyText/TextCopy any pointers on the change that fixed it in catel, since  https://github.com/Catel/Catel/blob/develop/src/Directory.build.shared.implicit.props#L51 no longer exists

**Comment by GeertvanHorrik** [comment]
Here is the changeset that fixed it at the time:

https://github.com/Catel/Catel/commit/ef1129ee2d3aee3881f1a6edfa5b398d24daa95f#diff-d181c6c9971de4f19a768eb0a35e444ab1462d21456b0bb6e36c95162a701568

I checked your project file, but couldn't find this part:

```
<LanguageTargets>$(MSBuildToolsPath)\Microsoft.CSharp.targets</LanguageTargets>
```

But hopefully it will give you pointers in the right direction.
