### ISSUE TITLE
Reference cpu-specific C++/CX dll from a C# cpu-specific uap lib in a multi targeted project

### ISSUE THREAD

**Issue by mfkl** [onovotny/MSBuildSdkExtras#148]
Hi,

I followed your [Creating Per-RuntimeIdentifier packages](https://github.com/onovotny/MSBuildSdkExtras#creating-per-runtimeidentifier-packages) readme steps and managed to get cpu specific (i.e. `win10-x86`, `win10-x64`) builds of my multi targeted lib for the `uap` tfm.

I need each of these dlls to reference a native C++/CX dll and I'm not quite sure how to do this. 

I followed your [blog post](https://oren.codes/2018/07/03/create-and-pack-reference-assemblies/) about reference assemblies but got this error when building.

```
1>C:\Program Files\dotnet\sdk\2.1.500\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(96,5): error NETSDK1013: The TargetFramework value '_,Version=v0.0' was not recognized. It may be misspelled. If not, then the TargetFrameworkIdentifier and/or TargetFrameworkVersion properties must be specified explicitly.
```

I'm not even sure the reference assemblies is the correct approach for my goal. All the code is here https://github.com/mfkl/libvlcsharp/tree/uwp.

Any advice would be really appreciated.

**Comment by mfkl** [comment]
Worked around it.

**Comment by onovotny** [comment]
What was the workaround?

**Comment by mfkl** [comment]
Rewriting the C++/CX code in [C#](https://github.com/mfkl/libvlcsharp/blob/feature/uwp/TestUWP/MainPage.xaml.cs)
