### ISSUE TITLE
Issues compiling with 3.0.100-preview-010184

### ISSUE THREAD

**Issue by glennawatson** [onovotny/MSBuildSdkExtras#151]
This issue does not exist with '3.0.100-preview-009812' only with '3.0.100-preview-010184'

My global.json file is as follows:
```
{
    "sdk": {
        "version": "3.0.100-preview-010184"
    },

     "msbuild-sdks": {
        "MSBuild.Sdk.Extras": "2.0.0-preview.14"
    }
}
```

When looking at the binary build log, it seems to be defaulting back to main visual studio Microsoft.Net.Sdk.props unlike 009812 which picked up the c:\program files\dotnet ones.

Will look through and see if I can find any reason for this myself.
[msbuild.binlog..zip](https://github.com/onovotny/MSBuildSdkExtras/files/2825185/msbuild.binlog.zip)

**Comment by glennawatson** [comment]
Further information

This does not happen with msbuild 16 installs.

This is mostly an issue with MSBuild 15 which is running on the Azure Devops machine (and if using MsBuild 15 locally).

**Comment by onovotny** [comment]
Two things:

1. .NET Core 3 preview 2 requires VS 2019 to build correctly if you need msbuild. VS 2017 won't work at all.
2. The v2 of the extras should work with the .NET Core 2.x SDK's and VS 2017. If there's an issue with that, that'd be a bug.

**Comment by glennawatson** [comment]
Will test and get back to you.

**Comment by glennawatson** [comment]
The other case conditions work fine. So closing this one and will have to coordinate getting a non-hosted agent for the moment for VS2019 builds.
