### ISSUE TITLE
[2.0.0-preview.14] dotnet pack not working

### ISSUE THREAD

**Issue by GeertvanHorrik** [onovotny/MSBuildSdkExtras#153]
I am using `dotnet pack` for multitargeted libraries (I believe the original reason was because I didn't want to issue a build, just create the packages based on an output folder). However... I now get this error:

```
C:\Users\geert\.nuget\packages\msbuild.sdk.extras\2.0.0-preview.14\Build\Workarounds.targets(27,5): error : If you are building projects that require targets from full MSBuild or MSBuildFrameworkToolsPath, you need to use desktop msbuild ('msbuild.exe') instead of 'dotnet build' or 'dotnet msbuild'
[C:\Source\catel\src\Catel.Core\Catel.Core.csproj]
An error occurred when executing task 'Package'.
Error: One or more errors occurred.
        .NET Core CLI: Process returned an error (exit code 1).
```

Will try to investigate why this happens and report back.

**Comment by onovotny** [comment]
You can't use dotnet build/pack for these.... you need to use msbuild /t:pack

The only way to use the dotnet test and possibly dotnet pack commands with these would be to also use the --no-build and --no-restore parameters.

**Comment by GeertvanHorrik** [comment]
I am using the NoBuild and NoRestore values ;-)

No need for you to dive into this yet, I want to make sure I prepare this correctly to prevent you losing any time.

**Comment by GeertvanHorrik** [comment]
Putting some other tickets here why I started using dotnet pack in the first place. I can't exactly remember, but I think the reason was that NoBuild wasn't working for the full visual studio pack.

* https://github.com/dotnet/cli/issues/9303
* https://github.com/dotnet/core-sdk/issues/192

**Comment by GeertvanHorrik** [comment]
Finally got CakeBuild to generate a binlog for the packing, hopefully I can use the $(NoBuild) property to check whether the warning can be ignored.

**Comment by GeertvanHorrik** [comment]
`'$(NoBuild)' != 'true'` seems to work. @onovotny, is there a switch I can use to completely disable the processing of the extras?

E.g.:

```
  <Choose>
    <When Condition="'$(NoBuild)' == 'true'">
      <PropertyGroup>
        <_SdkDisable>true</_SdkDisable>
      </PropertyGroup>
    </When>
  </Choose>
```

**Comment by GeertvanHorrik** [comment]
I can easily add this extra condition on all potential stuff that can lead to issues, but basically you never want processing when NoBuild is true?

**Comment by GeertvanHorrik** [comment]
Not even sure how I got this working in the past... I did play a bit with disabling some warnings, but it doesn't even work with .7 at the moment. Continuing investigation...

**Comment by GeertvanHorrik** [comment]
I implemented a workaround for now. Whenever a project file contains "uap10.0", I will pack with MSBuild (target = Pack, NoBuild = true), that seems to create the right packages for now.

I have no idea what recently changed that this no longer works, I just double checked the master branch of Catel (which was released 2 weeks ago), and that deployed fine using dotnet pack, uap and sdk extras.

**Comment by GeertvanHorrik** [comment]
Ok, this is getting interesting. The *only* thing I changed was removing the import of `Microsoft.CSharp.targets` (for #147). Turns out that was the key.

So instead of fully removing it, I am now defining this:

```
  <!-- Allow 'dotnet pack' usage, even when using UAP -->
  <PropertyGroup Condition="'$(NoBuild)' == 'true'">
    <!-- https://github.com/dotnet/sdk/issues/810 - the temporary project has the wrong file extension -->
    <LanguageTargets>$(MSBuildToolsPath)\Microsoft.CSharp.targets</LanguageTargets>
  </PropertyGroup>
```

This way, I can pack multitargeting stuff (uap, .net core, .net, etc) using dotnet pack. Is this something you would like to have integrated into the extras? It will only be applied when NoBuild is true, so shouldn't hit existing users (and you can remove the warning that you need to use the full msbuild).

**Comment by GeertvanHorrik** [comment]
On the other hand, since it looks like NoBuild works with full msbuild, there is no real need to use dotnet pack instead anymore, in that case this workaround can be skipped.

**Comment by GeertvanHorrik** [comment]
Yes, verified that full msbuild now also works. Will close this ticket, no need for `dotnet pack` or the workaround that makes uap supported for `dotnet pack`.
