### ISSUE TITLE
What happened to MSBuild.Sdk.Extras 1.0.0-rc4.23

### ISSUE THREAD

**Issue by AArnott** [onovotny/MSBuildSdkExtras#16]
I have builds failing in several repos lately because the `MSBuild.Sdk.Extras 1.0.0-rc4.23` package is no longer available. Did you somehow *remove* it from nuget.org? If you had unlisted it, I wouldn't expect it to break restore.

**Comment by AArnott** [comment]
Interestingly, I notice that your versioning scheme of any currently listed package uses a hyphen before the last number whereas the package version my repos were using had a period before the 23. Odd, since nuget doesn't support that, except very lately on modern clients. But now their gallery doesn't even list this version.

**Comment by onovotny** [comment]
That may have been a MyGet version from before NuGet supported semver2. That said, 1.0.6 is the one that works with the 2.0 SDK.

**Comment by AArnott** [comment]
I didn't have your myget feed on my package source list. So I don't think that was it.
I had the missing package in my local cache, so I uploaded it to my own myget feed. But ya, on machines with 2.0 SDK installed, that version is broken so I updated to 1.0.6 and removed my other NuGet workaround package from the project to fix the build break.

A mystery... that's probably not worth pursuing.
