### ISSUE TITLE
VS 2019 uap doesn't work

### ISSUE THREAD

**Issue by amerkoleci** [onovotny/MSBuildSdkExtras#160]
Hi,

I'm trying to build a VS 2017 solution with VS 2019, and I have 'uap10.0.16299' besides the TargetFrameworks, I get every time Required Windows SDK Version 10.0.16299.0 is not installed.

SDK's are installed of course I can build normal UWP project.

**Comment by amerkoleci** [comment]
This happens with VS2017 as well with 2.0.24 of nuget release, works well with 1.6.68

**Comment by onovotny** [comment]
Closing due to age. Please reopen if still an issue with VS 2019

**Comment by skarllot** [comment]
@onovotny This is still an issue

**Comment by onovotny** [comment]
Do you have a repro? I have uap10.0.16299 as a tfm in my test projects and can’t repro

**Comment by skarllot** [comment]
I'll try it, but I suspect that this happens because my installation is on
D:.

Em ter, 6 de ago de 2019 17:01, Oren Novotny <notifications@github.com>
escreveu:

**Comment by onovotny** [comment]
It's adding a reference to it here:
https://github.com/onovotny/MSBuildSdkExtras/blob/master/Source/MSBuild.Sdk.Extras/Build/LanguageTargets/Windows.targets#L26

It should be looking in the ProgramFiles32 directory for the Windows SDK location.
