### ISSUE TITLE
Build error on Visual Studio 16.1.0

### ISSUE THREAD

**Issue by YZahringer** [onovotny/MSBuildSdkExtras#166]
I have several compilation errors after updating Visual Studio to version 16.1.0. I use MSBuild.Sdk.Extras/2.0.24.

> NETSDK1005 Assets file 'Project.Shared\obj\project.assets.json' doesn't have a target for 'UAP,Version=v10.0.16299'. Ensure that restore has run and that you have included 'uap10.0.16299' in the TargetFrameworks for your project. C:\Program Files\dotnet\sdk\2.2.204\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.target

**Comment by onovotny** [comment]
That's a bug in 16.1: https://github.com/dotnet/project-system/issues/4854

**Comment by MSiccDev** [comment]
Any ideas to work around this until it gets fixed?

**Comment by glennawatson** [comment]
According to the bug you can side-by-side install previous versions of visual studio 16. See Oren's link above for details. I wouldn't be surprised if the fix is out this week though.

**Comment by onovotny** [comment]
Closing as external. The fix will be in VS 2019 16.1.2.

**Comment by SimonCropp** [comment]
@onovotny did u forget to close?

**Comment by onovotny** [comment]
Was waiting for 16.1.2 to be released first

**Comment by SimonCropp** [comment]
@onovotny ok good plan :)

**Comment by onovotny** [comment]
16.1.2 is available with the fix: https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#16.1.2

**Comment by jamesmcroft** [comment]
Interestingly this issue has cropped back up again so it seems. Package version is 2.0.54 and .NET Core SDK is 3.1.201

**Comment by jalbertSyncroTech** [comment]
We're also seeing this with the latest VS 16.5.4. I've added a comment to the original dotnet bug report.

**Comment by jalbertSyncroTech** [comment]
This seems to be the same issue as https://github.com/novotnyllc/MSBuildSdkExtras/issues/200
