### ISSUE TITLE
[Xamarin.Android] 'obj\Release\monoandroid81\Resource.Designer.cs' could not be found

### ISSUE THREAD

**Issue by xen2** [onovotny/MSBuildSdkExtras#174]
Started to happen once I updated VS2019 from 16.1.6 to 16.2.0

Seems to be due to https://github.com/onovotny/MSBuildSdkExtras/blob/master/Source/MSBuild.Sdk.Extras/Build/Platforms/Xamarin/Xamarin.Android.targets#L11
(until line 18).

Maybe those parameters are interpreted differently in latest Xamarin Android.

Note: this is a big blocker, can't compile anything without ugly workaround to remove the `Compile` from line 18.

**Comment by xen2** [comment]
Note: my current workaround is to actually set `AndroidResgenFile` to a non-existing file, so that https://github.com/onovotny/MSBuildSdkExtras/blob/master/Source/MSBuild.Sdk.Extras/Build/Platforms/Xamarin/Xamarin.Android.targets#L18 doesn't add a non-existing file.

**Comment by xen2** [comment]
Quick guess (since I don't have the old version anymore):
maybe it used to generate empty file before if there was nothing to write, but maybe in latest Xamarin.SDK it doesn't generate the file at all anymore?

This might be the actual change:
https://github.com/xamarin/xamarin-android/commit/ea6853a7568a1551b2784651702bec339c011ed3#diff-d07d3a1d454b339218b793dedae96995

**Comment by xen2** [comment]
Quick workaround:

```
  <Target Name="_RemoveNonExistingResgenFile" BeforeTargets="CoreCompile" Condition="'$(_SdkSetAndroidResgenFile)' == 'true' And '$(AndroidResgenFile)' != '' And !Exists('$(AndroidResgenFile)')">
    <ItemGroup>
      <Compile Remove="$(AndroidResgenFile)"/>
    </ItemGroup>
  </Target>
```

**Comment by onovotny** [comment]
I can't seem to repro this in 16.3 preview 1. Does it repro for you there? If so, can you attach a small repro project? In my test library project, I see a Resource.Designer.cs in the obj\MonoAndroid81 directory.

**Comment by skarllot** [comment]
@xen2 Could fix to 1.6 branch too, because I'm stuck with this version because UWP support.

**Comment by Perksey** [comment]
Getting this too, thanks for the workaround @xen2

**Comment by RLittlesII** [comment]
https://github.com/onovotny/MSBuildSdkExtras/issues/174#issuecomment-517740808 fixed our issue.  We added it to every project that targeted `MonoAndroid`

**Comment by jamesmontemagno** [comment]
I had an odd dependency on the new billing library and it has a dependency on annotations. I had to add the resgen fix and turn off designtime builds too: https://github.com/jamesmontemagno/InAppBillingPlugin/commit/1220af465fe6045cbf2b9e19b13909a0f0355523

**Comment by onovotny** [comment]
I'm still unable to repro this locally....

I added @jamesmontemagno's files and it builds https://github.com/onovotny/MSBuildSdkExtras/blob/repro-attempt-for-designer/Tests/ClasslibWithNuGetSdkRef/ClasslibWithNuGetSdkRef.csproj

**Comment by onovotny** [comment]
Can you try Extras `2.0.41`? Should have a fix for this.

**Comment by JulienTheron** [comment]
Same issue here. VS2019 16.2 with Extras 2.0.41.

**Comment by TSIoT** [comment]
Same issue here. VS2019 16.2.3 with Extras 2.0.41
But work fine in VS2017 15.9.15 with Extras 2.0.41

**Comment by Perksey** [comment]
Same issue here. Rider 2019.2 with Extras 2.0.41
