### ISSUE TITLE
[Xamarin.Android] 'obj\Release\monoandroid81\Resource.Designer.cs' could not be found 

### ISSUE THREAD

**Issue by RLittlesII** [onovotny/MSBuildSdkExtras#181]
The following [Splat Build](https://dev.azure.com/dotnet/ReactiveUI/_build/results?buildId=20643&view=logs&j=2d2b3007-3c5c-5840-9bb0-2b1ea49925f3) fails with MsBuild.Sdk.Extras v2.0.41

I explicitly put in the work around detailed https://github.com/onovotny/MSBuildSdkExtras/issues/174#issuecomment-517740808 last week to get the builds back green.  https://github.com/reactiveui/splat/pull/390/

As you can see from the above output on the latest build, when I remove the work around with MsBuild.Sdk.Extras 2.0.41 [here](https://github.com/reactiveui/splat/commit/4aa3838bf7b7ae3bac295ab70d8fee03f6d63c01), I still received the error.

Related to #174

**Comment by onovotny** [comment]
Is this about DesignTime or about the ResGen file?

I haven't been able to repro locally but made changes based on reading the targets:

https://github.com/onovotny/MSBuildSdkExtras/blob/master/Source/MSBuild.Sdk.Extras/Build/Platforms/Xamarin/Xamarin.Android.targets#L12-L14

We're not even setting the ResGen file anymore, nor are we setting the private `_SdkSetAndroidResgenFile` anymore either.

**Comment by RLittlesII** [comment]
This is about the ResGen.  I thought that was fixed in 2.0.41, but taking out the work around still generates the error.

**Comment by RLittlesII** [comment]
I've got another build issue blocking me from reproducing this locally.  When I can I will provide more information.

**Comment by RLittlesII** [comment]
Attached: [binlog.zip](https://github.com/onovotny/MSBuildSdkExtras/files/3523349/binlog.zip)

This is from a local build where I was able to reproduce the same issue on that same commit.

**Comment by TSIoT** [comment]
@RLittlesII Same issue as yours when I use VS2019. But it work fine on VS2017, so I change IDE to let my work could keep going.

**Comment by onovotny** [comment]
From that binlog, the best I can tell is that `GenerateResourceDesigner` from `Xamarin.Android.Common.targets` isn't writing the output file.

`_AndroidResourceDesignerFile` is calculated by the targets to be `obj\Release\monoandroid81\81\Resource.designer.cs`, based on the IntermediateOutputPath:
https://github.com/xamarin/xamarin-android/blob/master/src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets#L1215

That value is always set. It's supposed to be the output file here:
 https://github.com/xamarin/xamarin-android/blob/master/src/Xamarin.Android.Build.Tasks/Xamarin.Android.Common.targets#L1298

@jamesmontemagno any ideas?

**Comment by onovotny** [comment]
Also cc @jonathanpeppers and @jonpryor for some 👀

**Comment by jonathanpeppers** [comment]
This came up here: https://developercommunity.visualstudio.com/content/problem/672764/building-xamarin-multi-targeted-plugin-fails-unabl.html

We found that 16.2 has this regression, but it is already fixed in 16.3 previews.

A workaround is to add this MSBuild property to your project:
```xml
<AndroidUseIntermediateDesignerFile>False</AndroidUseIntermediateDesignerFile>
```

Going forward, we are putting these tests in, so we don't break MSBuild.Sdk.Extras accidentally: https://github.com/xamarin/xamarin-android/pull/3523

**Comment by onovotny** [comment]
Thanks @jonathanpeppers for the quick reply!

Is there anything that should be updated/changed/defaulted differently here:

https://github.com/onovotny/MSBuildSdkExtras/blob/master/Source/MSBuild.Sdk.Extras/Build/Platforms/Xamarin/Xamarin.Android.targets

That's what has most of the things that came out of the older style csproj.

**Comment by glennawatson** [comment]
ReactiveUI put the `AndroidUseIntermediateDesignerFile` in our `directory.target.props` and it solved the build error for us.

**Comment by onovotny** [comment]
Closing as external.
