### ISSUE TITLE
Adding System.Drawing.Common to NuGet for Xamarin.iOS

### ISSUE THREAD

**Issue by jamesmontemagno** [onovotny/MSBuildSdkExtras#192]
When i package up my media plugin I am getting this stuff: https://github.com/jamesmontemagno/MediaPlugin

![image](https://user-images.githubusercontent.com/1676321/66780717-68a23500-ee86-11e9-80e3-5e58e2866bfc.png)

Java Interop is usually fine, but this System.Drawing.Common is new and causing install issues for some. https://github.com/jamesmontemagno/MediaPlugin/issues/756

**Comment by onovotny** [comment]
That's all done by the NuGet targets that collect Framework references. A couple things would be helpful.

1. a binlog
2. if you want to prevent it, you can probably do an Update PrivateAssets=All to the item.

**Comment by jamesmontemagno** [comment]
Where would I put the "PrivateAssets=All"?

**Comment by jamesmontemagno** [comment]
So, i think it is something with VS 2019. If I build in 2017 I don't get the reference added. Is there a way in my csproj to force stuff not to be added?

**Comment by onovotny** [comment]
You can always update the Item to say PrivateAssets=all, you'd need a target that runs at the right point to update it (BeforeBuild possibly). A binlog from both could help.

**Comment by jamesmontemagno** [comment]
See: https://github.com/xamarin/xamarin-macios/issues/7249

<DisableExtraReferences>true</DisableExtraReferences>

Fixes it
