### ISSUE TITLE
FxCopCmd deprecation warning

### ISSUE THREAD

**Issue by bclothier** [onovotny/MSBuildSdkExtras#193]
I'm testing this SDK for our project and when migrating from Sunburst SDK to this SDK, I got warnings about the usage of deprecated `FxCopCmd` and to use `FxCop` instead. Since we don't explicitly use `FxCopCmd`, I'm led to thinking that it's something to do with using the SDK. 

Is it a matter of setting something in the project file?

**Comment by onovotny** [comment]
I’m not sure but nothing in the SDK mentions or calls FxCop.

**Comment by bclothier** [comment]
With some further analysis, our change of SDK actually wasn't the reason why. We actually had a line in our base `.csproj`:

```
<RunCodeAnalysis>true</RunCodeAnalysis>
```

which actually maps to running code analysis using FxCopCmd, as [documented here](https://docs.microsoft.com/en-us/visualstudio/code-quality/fxcop-analyzers-faq?view=vs-2019#does-the-runcodeanalysis-msbuild-project-property-run-analyzers). The warning seems to be a new thing for Visual Studio 2019 and since we weren't able to build using 2019 until we switched to this SDK, it was a red herring.

My apologies.
