### ISSUE TITLE
Profile259 only works when omitting Xamarin platforms

### ISSUE THREAD

**Issue by AArnott** [onovotny/MSBuildSdkExtras#2]
Although this works:
portable-net45+win8+wpa81+wp8

This doesn't:
portable-net45+win+wpa81+wp80+MonoAndroid10+xamarinios10+MonoTouch10

> C:\Users\andarno\.nuget\packages\msbuild.sdk.extras\1.0.0-rc4-17\build\netstandard1.0\MSbuildSdkExtras.Common.targets(106,5): error : The specified TFM 'portable-net45+win+wpa81+wp80+MonoAndroid10+xamarinios10+MonoTouch10' is not valid. Check that it's a valid combination: http://portablelibraryprofiles.apps.stephencleary.com/ [C:\git\Validation.my\src\Validation\Validation.csproj]

Both are equivalent to Profile259. But if I leave out the Xamarin platforms then Xamarin projects don't accept the package (IIRC).

**Comment by onovotny** [comment]
Yeah, I can't correctly account for optional tfms as I have to check the count of tfms to ensure all of the contains searches work.

**Comment by onovotny** [comment]
I'm open to ideas on how to do this if we can do it through static property evaluation

**Comment by AArnott** [comment]
I don't understand enough of the inner workings of PCL profile picking to suggest a way -- yet. But if you can write up the properties that would need to be set (using C# if you want) I'll take a look to see if I could conjure up some msbuild that could do it.
Alternatively, can I just hard-code a propertygroup to do it?

**Comment by onovotny** [comment]
I think the Xamarin bugs have long since been fixed though, adding those tfms shouldn't be need at all. It was a hack Xamarin did before they had proper nuget support. Nowadays, they're using the mainline nuget binaries directly and the compatibility checks should br working normally.

**Comment by AArnott** [comment]
oh! Well, that would be fine then.

**Comment by AArnott** [comment]
I'll test that in VS2015 later today and close this if it works.

**Comment by AArnott** [comment]
It works on a Profile259 PCL and on a Xamarin.Android app, without explicitly listing the Xamarin TFMs.

The only issue is I need to clear out the dependencies for the Xamarin platforms explicitly to avoid installing dozens of corefx packages. I'll have to figure that out myself as I doubt that's within scope of this project.

**Comment by onovotny** [comment]
There's talk about back porting the netstandard.library trimming they're doing for 2.0 into a servicing release here:
https://github.com/dotnet/corefx/issues/15735

Original trimming: https://github.com/dotnet/standard/pull/215
