### ISSUE TITLE
Please add Rider support

### ISSUE THREAD

**Issue by aka-STInG** [onovotny/MSBuildSdkExtras#22]
Currently build fails with the following error:

  MSBuildSdkExtras.Common.targets(114, 5): [null] C:\Users\OlegI\.nuget\packages\msbuild.sdk.extras\1.1.0-beta.69\build\netstandard1.0\MSBuildSdkExtras.Common.targets(114,5): error : The specified language targets for monoandroid71 is missing. Ensure correct tooling is installed for 'monoandroid'

**Comment by onovotny** [comment]
This isn't up to me, you need to take it up with JetBrains.

**Comment by aka-STInG** [comment]
Actually I managed to even debug Xamarin Android project! The issue is that Rider uses some different way to restore nuget packages. Ones I manually restored packages for solution from command line, everything builds and debugs as a charm!

Unfortunately Visual Studio can only build such projects, Debug/Deploy is not possible.

**Comment by onovotny** [comment]
Again, nothing I can do here, you need to take this up with JetBrains. If there's a magic set of targets/properties that would make this work, I'm happy to take a PR, but I'm not going to spend any time on it.
