### ISSUE TITLE
MonoAndroid requires API Level 15

### ISSUE THREAD

**Issue by lennoncork** [onovotny/MSBuildSdkExtras#24]
The packages worked great and I was able to compile the monoandroid project successfully. I did have to install some additional API levels (from 17 to 15), so maybe there's some configuration I'm missing to specify minimum API. I also had to set TargetFramework to monoandroid403 instead of just monoandroid, not sure of the exact implication, but works all the same. Thanks you very much for the package.

**Comment by totht91** [comment]
Can you provide an example android csproj with this new package?

**Comment by onovotny** [comment]
xunit for devices uses it:
https://github.com/xunit/devices.xunit/blob/master/src/xunit.runner.devices/xunit.runner.devices.csproj

You can only use it for class libraries, not application head's currently.

**Comment by totht91** [comment]
Thanks, this is what I was looking for.

**Comment by lennoncork** [comment]
This was a user error, updating target framework to monoandroid71 and/or monoandroid80 dropped the minimum dependency. Keep up the good work!
