### ISSUE TITLE
UWP - XAML Build Defaults & Architecture Dependencies

### ISSUE THREAD

**Issue by WilliamABradley** [onovotny/MSBuildSdkExtras#25]
Hey @onovotny, I've been reverse engineering this from UWPCommunityToolkit for use in my personal projects, and I have hit two road blocks.

In UWPCommunityToolkit, I see that the XAML Documents are marked as Pages, and have the Msbuild:Compile Custom Tool marked, although it is not reflected in the .csproj, is there a way to achieve this, I can't figure it out, without having to define it in the Cspoj, which adds even more Lines than original.
When I have done this, it has marked the Build Action as None with no Custom Tool.

The second road block I have hit is for Architecture Specific References I have. I am trying to convert to this Project Style so I can easily package my Shared Library with NuGet, so I have bundled Microsoft.Store.Services.SDK, and it's references for the Engagement Framework and Advertising SDK, which also bundles VC++ 2015. These dependencies fail when using AnyCPU, is there any way to reference these from this Project Style, and have it produce a clean NuGet Package?

**Comment by WilliamABradley** [comment]
@onovotny Any Thoughts?

**Comment by onovotny** [comment]
In the UWP community toolkit, those Page's are defined in the Directory.build.props here:

https://github.com/Microsoft/UWPCommunityToolkit/blob/master/Directory.Build.props#L63-L66

Note, they're conditionally included and they're in a Choose/When as the legacy project system complains about conditional includes if they're directly in an ItemGroup/PropertyGroup.

Some of the conditional includes are in the targets:
https://github.com/Microsoft/UWPCommunityToolkit/blob/master/Directory.Build.targets

So between the props/targets, that should get you what you need. Any reference, `PackageReference`/`ProjectReference` can be conditional, so easy to pivot on the architecture.

**Comment by WilliamABradley** [comment]
Ah, I see.
Would there be any way to Include an Architecture Dependent Reference into a .NET Standard Library?
The Microsoft.Store.Services.SDK NuGet Package Works, but when trying to reference the Advertising SDK or the Engagement Framework, it complains that it requires an Architecture, not AnyCPU.

**Comment by onovotny** [comment]
That gets tricky, you can do it by TFM, and you can include a targets file that gets auto-included, but you can't have a nuget reference in a targets file (since it only does one restore pass).

**Comment by WilliamABradley** [comment]
Hmm, that seems a bit beyond my knowledge, I think I will just include the Store SDK inside of all my projects instead of inside the package for now.
