### ISSUE TITLE
C# define Profile* for PCLs

### ISSUE THREAD

**Issue by AArnott** [onovotny/MSBuildSdkExtras#3]
Consider adding this to your common .targets

```xml
  <PropertyGroup Condition="'$(_ExtrasShortFrameworkIdentifier)' == 'portable'">
    <DefineConstants>$(DefineConstants);$(TargetFrameworkProfile)</DefineConstants>
  </PropertyGroup>
```

That way folks can just say `#if Profile328` the same way they can say `#if NET40`.

**Comment by onovotny** [comment]
Looking at this, any suggestions for what you think it should be for PCL?
https://github.com/onovotny/sdk/blob/8bc512032f3955204f2bb0c76fe8063ade48cffa/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.BeforeCommon.targets#L111-L123

I'm working on integrating it with the main SDK so I'd like it to be in the same pattern there.

`NETPORTABLE_328`? `PCL328`, `PROFILE328`, `PORTABLE_328`?

**Comment by AArnott** [comment]
> I'm working on integrating it with the main SDK 

Awesome.

PROFILE328 would be fine. I think PROFILE_328 or PORTABLE_328 would neither align with their pattern of IDMAJOR_MINOR nor be particularly intuitive. I think folks think of these either as "profile 259" or "portable-lots+of+frameworks". The latter of which couldn't make a good symbol, so that leaves me with PROFILE259. NETPORTABLE_PROFILE328 might also work, but it's a bit lengthy.

**Comment by onovotny** [comment]
Do you think it should get two defines? NETPORTABLE and PROFILEnnn? I'm thinking yes so that the right ifdef's can be done but I'm not sure?

**Comment by AArnott** [comment]
What are "the right ifdef's" you refer to? I don't know why we'd define two. Are you talking about literally just `NETPORTABLE` (with no suffix)? I'm not sure what I would condition on that, since the profile in particular is what determines the surface area.

**Comment by onovotny** [comment]
Fair point, there's probably not much use for a standalone `NETPORTABLE` define. BTW, the latest CI version should have this completed in it (using `PORTABLEnnn`).

**Comment by AArnott** [comment]
Great. Thanks.
