### ISSUE TITLE
WPF: Adding xmlns with clr-namespace to XAML breaks build with cryptic error message

### ISSUE THREAD

**Issue by BrunoJuchli** [onovotny/MSBuildSdkExtras#32]
Dear Oren
Today I tried converting a bare WPF Project, i.E. one that was created by VS 15.5.7 New -> Project -> WPF App (.Net Framework) to the new csproj sdk format. I got stuck with:

> 1>C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\Microsoft.WinFx.targets(419,45): error MSB4057: The target "CoreCompile" does not exist in the project.

Removing the following line from MainWindow.xaml fixes the build:

> xmlns:local="clr-namespace:SdkCsprojWpfSpike"

ATM I'm quite perplexed how this can have any effect on the build outcome, but I'd guess it's about the WPF two-pass build...?!

--------------

Notably, (not) having the same line @ App.xaml doesn't matter.

---------------

Sample Project
---------

Using your sample project I can reproduce the same issue.
The steps I performed:

## 1 ./Samples/WpfApplication/MainWindow.xaml
insert the following as Line 8:

> xmlns:local="clr-namespace:WpfApplication"

![image](https://user-images.githubusercontent.com/2090172/36538542-332f3254-17d4-11e8-9762-c7466b114386.png)

## 2 ./Samples/WpfApplication/WpfApplication.csproj
I've had to change the target framework to **net471** - because I don't have net462 installed.

## 3 Open Csproj & Build
.. and you'll see
> 1>C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\Microsoft.WinFx.targets(419,45): error MSB4057: The target "CoreCompile" does not exist in the project.

------------------

I'd be happy providing a PR for the readme/wiki page to document this, at the least. Any directions for a header, where to place it the document?

**Comment by BrunoJuchli** [comment]
Also, adding a User Control (WPF) immediately breaks the build:

![image](https://user-images.githubusercontent.com/2090172/36538807-0ad063cc-17d5-11e8-9463-5142fe7733bc.png)

Same solution. Remove the xmlns:local:

![image](https://user-images.githubusercontent.com/2090172/36538829-18fa53c2-17d5-11e8-9f3f-51dcc5924fbe.png)

**Comment by onovotny** [comment]
I haven't fully documented this yet as there are some nasty workarounds needed that will be going away soon-ish, I hope.

For now, NuGet Package Explorer is a good example to look at:
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/master/PackageExplorer/NuGetPackageExplorer.csproj

Note the workarounds at the top and bottom of the file:
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/master/PackageExplorer/NuGetPackageExplorer.csproj#L3-L7
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/master/PackageExplorer/NuGetPackageExplorer.csproj#L39-L40

**Comment by BrunoJuchli** [comment]
@onovotny 
Thanks for the quick answer.
That's a fix for the same issue (https://github.com/NuGet/Home/issues/5894) that the sample project also contains a fix for, though it's slightly different.
I'll see what difference it makes and report back.

Also, out-of-the-box the NuGetPackageExplorer doesn't compile for me. Got a copy of the source code as zip, unpacked, and first was confronted with VS migration dialog + afterwards it didn't compile properly.
Can I ask what version of VS you are using?

Thanks!

**Comment by BrunoJuchli** [comment]
@onovotny 
Thanks again - the lines you referenced in PackageExplorer did help fixing this issue.
In my case, the significant different was made by

https://github.com/onovotny/MSBuildSdkExtras/blob/master/Samples/WpfApplication/WpfApplication.csproj#L7
vs
https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/blob/master/PackageExplorer/NuGetPackageExplorer.csproj#L7

**Comment by onovotny** [comment]
I'm using VS 2017 15.5 for NuGet Package Explorer.

**Comment by glennawatson** [comment]
I was having the exactly same issue and replacing that line did the trick for me as well.
