### ISSUE TITLE
'The target "Build" does not exist in the project' for PCL profiles 2 and 328

### ISSUE THREAD

**Issue by coldacid** [onovotny/MSBuildSdkExtras#35]
Target framework strings:

* `portable-net4+sl40+win8+wp70` (Profile2)
* `portable-net4+sl50+win8+wpa81+wp8` (Profile328)

Command line and output:

```
PS> dotnet pack /bl
Microsoft (R) Build Engine version 15.5.180.51428 for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

C:\Program Files\dotnet\sdk\2.1.4\MSBuild.dll /bl /Logger:Microsoft.DotNet.Tools.MSBuild.MSBuildLogger,C:\Program Files\dotnet\sdk\2.1.4\dotnet.dll /m /restore /t:pack /v:m .\Structurizr.Annotations.csproj
  Restoring packages for C:\Users\ccharabaruk\Repos\structurizr-dotnet\Structurizr.Annotations\Structurizr.Annotations.csproj...
  Generating MSBuild file C:\Users\ccharabaruk\Repos\structurizr-dotnet\Structurizr.Annotations\obj\Structurizr.Annotations.csproj.nuget.g.props.
  Generating MSBuild file C:\Users\ccharabaruk\Repos\structurizr-dotnet\Structurizr.Annotations\obj\Structurizr.Annotations.csproj.nuget.g.targets.
  Restore completed in 542.19 ms for C:\Users\ccharabaruk\Repos\structurizr-dotnet\Structurizr.Annotations\Structurizr.Annotations.csproj.
C:\Users\ccharabaruk\Repos\structurizr-dotnet\Structurizr.Annotations\Structurizr.Annotations.csproj : error MSB4057: The target "Build" does not exist in the project.
C:\Users\ccharabaruk\Repos\structurizr-dotnet\Structurizr.Annotations\Structurizr.Annotations.csproj : error MSB4057: The target "Build" does not exist in the project.
  Structurizr.Annotations -> C:\Users\ccharabaruk\Repos\structurizr-dotnet\Structurizr.Annotations\bin\Debug\netstandard1.0\Structurizr.Annotations.dll
PS>
```

Binlog output: [msbuild.binlog.zip](https://github.com/onovotny/MSBuildSdkExtras/files/1764070/msbuild.binlog.zip)

**Comment by coldacid** [comment]
This happens with 1.1.0 and 1.2.x

**Comment by onovotny** [comment]
@coldacid you cannot use `dotnet` for these projects, you have to use `msbuild.exe`. There's a difference in the way they look up targets, as well as which runtime it executes on.

Try msbuild /t:pack

**Comment by coldacid** [comment]
Will there be support for `dotnet` down the road then?

**Comment by Nirmal4G** [comment]
People are confusing with core and desktop msbuild, we should add the logic to tell them if they are targeting non-xplat stuff, we should just emit a warning and halt the build. With `WarnAndContinue` we should give them opt-out per framework case.

Any thoughts on this...?

**Comment by coldacid** [comment]
I ended up just manually building out everything I needed in my csproj file to support the portable targets without having to completely redo my build pipeline. If MSBuildSdkExtras can't work with Core MSBuild then there should be more obvious notices about this even before adding it to a project (i.e. mention it in the package description) in addition to emitting an explicit warning or error at build time.

**Comment by onovotny** [comment]
@coldacid The readme on this repo does mention that.

It's also not clear that `dotnet` build can properly build PCL's. PCL required the right reference assemblies to be installed and located. I do not believe the .NET Core SDK contains those.

**Comment by coldacid** [comment]
@onovotny it's not good enough to be mentioned in the repo readme, it should be visible directly on the nuget.org page for the package and in any package manager frontend for NuGet that displays package metadata.

As for whether or not the Core SDK can be used to build PCLs, building was successful by adding this to the csproj:

```
  <PropertyGroup Condition="'$(TargetFramework)' == 'portable40-net40+sl4+win8+wp7'">
    <TargetFrameworkIdentifier>.NETPortable</TargetFrameworkIdentifier>
    <TargetFrameworkVersion>v4.0</TargetFrameworkVersion>
    <TargetFrameworkProfile>Profile2</TargetFrameworkProfile>
    <DefineConstants>$(DefineConstants);PORTABLE2</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)' == 'portable40-net40+sl5+win8+wp8+wpa81'">
    <TargetFrameworkIdentifier>.NETPortable</TargetFrameworkIdentifier>
    <TargetFrameworkVersion>v4.0</TargetFrameworkVersion>
    <TargetFrameworkProfile>Profile328</TargetFrameworkProfile>
    <DefineConstants>$(DefineConstants);PORTABLE328</DefineConstants>
  </PropertyGroup>
```

Examining the generated DLLs for the portable targets shows them to have correct metadata and properly reference mscorlib for the selected profiles (there's no need to reference other assemblies for this project). So long as Visual Studio is installed, even if not directly used by Core SDK, the Core MSBuild knows where to find the PCL reference assemblies.

This also stands for targeting even .NET Framework v2.0 although in that case I also needed to add the `FrameworkPathOverride` property to point to the framework directory `$(windir)\Microsoft.NET\Framework\v2.0.50727` for that target to build.

**Comment by berlamont** [comment]
You should at the very least read the Readme. Saying that the Readme is not sufficient is silly.

**Comment by Nirmal4G** [comment]
@berlamont It's not silly, Most people won't even to go NuGet.org, they just install from the NuGet UI from VS and they read the description there (_they'll go only if that description tells them to_)!

On the other hand, I was experimenting with the `Extras.Sdk` to display the error on such cases, I'll drop a PR soon, If I can get it working properly for all the TFMs!

**Comment by berlamont** [comment]
How do you know how to utilize said nuget package? Are you saying the package name with or without the description has been sufficient for you?
