### ISSUE TITLE
Project build fails if AssemblyName != name of project

### ISSUE THREAD

**Issue by batzen** [onovotny/MSBuildSdkExtras#44]
Hi,

my build fails because my project file is named "Fluent.Ribbon.csproj" but i specify "Fluent" as `AssemblyName`.
Due to this the check `('$(MSBuildProjectExtension)' == '.tmp_proj' and Exists('$(MSBuildProjectDirectory)\$(AssemblyName).csproj')` fails and the correct `_SdkLanguageName` is not set.
I tried to work around this issue by adding things like `MyProjectName` to the original csproj file and modify the check to also check for `$(MyProjectName).csproj` but the value of `MyProjectName` is empty in the `.tmp_proj` file.

Any suggestions on how to solve this issue, without adding `_SdkLanguageName` to something like Directory.build.props?

**Comment by onovotny** [comment]
This is now fixed in the latest CI build.

**Comment by onovotny** [comment]
This fix is now on NuGet as well. Note that you need .NET 4.7.2 installed on the build agent for the fix to work.
