### ISSUE TITLE
Consider built-in PackageTargetFallback support

### ISSUE THREAD

**Issue by AArnott** [onovotny/MSBuildSdkExtras#5]
It's annoying when targeting .netstandard that compatible PCLs aren't automatically considered compatible. Folks have to define the `PackageTargetFallback` msbuild property manually to name the portable profile that should be allowed.

Can this package add smarts around this to define the right values for this property based on the TargetFramework, when it is .netstandard?

**Comment by onovotny** [comment]
I was thinking about that.... do you know if it's an explicit list that has to be or only the "highest," "most compatible" version that needs to be there?

Wondering what the best choice is for each .NET Standard version. Happy to add that in.

**Comment by AArnott** [comment]
Some folks on the nuget team have been very negative toward use of this property. Others have expressed high caution, saying it doesn't really do what you think it's doing... so I would keep it out of your original PR to keep the uncontestable stuff more likely to get in.

**Comment by AArnott** [comment]
As for the answers to your questions, I don't know.

**Comment by onovotny** [comment]
Yeah, if I do this, I'd submit it as a separate PR to not mix purposes. I'm really not sure why this isn't already "in-box" though. Despite the desire to get people off of pcl profiles, all it does is cause developer pain until enough of the ecosystem has updated to netstandard :/

**Comment by AArnott** [comment]
Yup. I think some nuget folks use it as a forcing function to get authors to update their packages to .netstandard. But I agree: it's mostly just pain, and if this alleviates the pain, but slows down migration slightly, IMO that's still a net win.

**Comment by onovotny** [comment]
I think we can close this as the 2.0 SDK seems to do this already.
