### ISSUE TITLE
Adding MSBuildSdkExtras to csproj causes error in VS 15.6.3

### ISSUE THREAD

**Issue by feO2x** [onovotny/MSBuildSdkExtras#50]
After I upgraded VS to 15.6.3, the IDE could not load csproj files that target MSBuildSdkExtras via `<Project Sdk="MSBuild.Sdk.Extras/1.2.2">`:

![image](https://user-images.githubusercontent.com/7884158/37618588-ff153152-2bb6-11e8-9f25-eb3f19282b5e.png)

**Steps to reproduce:**
- Update Visual Studio to 15.6.3
- Create a new solution and add a class library project targeting `netstandard2.0`
- Exchange the SDK with MSBuildSdkExtras

**Error message:**
D:\Programming\MSBuildSdkExtrasVs15.6.3Error\MSBuildSdkExtrasVs15.6.3Error.csproj : error  : Project file is incomplete. Expected imports are missing.

When I revert back to `<Project Sdk="Microsoft.NET.Sdk">`, I can load the project and compile it. However, I have the suspicion that there is something wrong with 15.6.3 because when I add `netstandard1.0` as a TFM then the project will not build in visual studio, showing the following error message:

Error		Assets file 'D:\Programming\MSBuildSdkExtrasVs15.6.3Error\obj\project.assets.json' doesn't have a target for '.NETStandard,Version=v1.0'. Ensure that restore has run and that you have included 'netstandard1.0' in the TargetFrameworks for your project.	MSBuildSdkExtrasVs15.6.3Error	C:\Program Files\dotnet\sdk\2.1.102\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets	167	

 However, it works fine when I compile it via msbuild on the command prompt directly.

**Comment by onovotny** [comment]
Can repro, looking into it.

**Comment by xxMUROxx** [comment]
I have the same error like @feO2x . Unfortunately no project that uses `MSBuild.Sdk.Extras/1.2.2` opens.

**Comment by feO2x** [comment]
Should we report this to the VS team or the ReSharper team? Did you do that already?

**Comment by onovotny** [comment]
The VS team is looking into it.

**Comment by jeffkl** [comment]
We're working on a [temporary fix](https://github.com/dotnet/sdk/issues/2068#issuecomment-374912033) and long term solution with JetBrains.

**Comment by glennawatson** [comment]
Just upgraded to 15.6.4 and still happens here.

**Comment by feO2x** [comment]
@glennawatson I just checked it and it works with ReSharper 2017.3.4:

![image](https://user-images.githubusercontent.com/7884158/37830619-fadf9264-2ea2-11e8-8406-0291163e90eb.png)

**Comment by glennawatson** [comment]
Where did you find the 2017.3.4, the latest on the website is 2017.3.3

**Comment by feO2x** [comment]
@glennawatson in Visual Studio, I went to the menu ReSharper -> Help -> Check for updates...

**Comment by glennawatson** [comment]
Obviously they haven't had a chance to update the website. Thanks that worked.

**Comment by AndreyAkinshin** [comment]
The problem is fixed in ReSharper 2017.3.5, everything works with all combinations of Visual Studio and .NET Core SDK.
You can find more technical details in the official blog post: https://blog.jetbrains.com/dotnet/2018/03/23/build-failures-visual-studio-15-6-3-resharper-ultimate-2017-3-5-rescue/

2017.3.4 also solves the problem, but it has some additional technical issues, so we had to release 2017.3.5 which solves all problems.
