### ISSUE TITLE
Add DEFINE constants so you can use them in code

### ISSUE THREAD

**Issue by GeertvanHorrik** [onovotny/MSBuildSdkExtras#51]
So the platforms thing is great, but sometimes it could get in the way. For example, see this project:

https://github.com/WildGums/Orc.Skia/blob/develop/src/Orc.Skia/Extensions/RectangleExtensions.cs

For this I have introduced DEFINES based on the target project:

```
  <!-- .NET Standard 2.0 -->
  <PropertyGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <DefineConstants>NETSTANDARD;NETSTANDARD2_0;NS;NS20</DefineConstants>
  </PropertyGroup>
  
  <!-- .NET 4.6 -->
  <PropertyGroup Condition=" '$(TargetFramework)' == 'net46' ">
    <DefineConstants>NET;NET46;NET460</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(TargetFramework)' == 'net461' ">
    <DefineConstants>NET;NET46;NET461</DefineConstants>
  </PropertyGroup>
  
  <PropertyGroup Condition=" '$(TargetFramework)' == 'net462' ">
    <DefineConstants>NET;NET46;NET462</DefineConstants>
  </PropertyGroup>

  <!-- .NET 4.7 -->
  <PropertyGroup Condition=" '$(TargetFramework)' == 'net47' ">
    <DefineConstants>NET;NET47;NET470</DefineConstants>
  </PropertyGroup>

  <!-- UAP 10.0 -->
  <PropertyGroup Condition=" '$(TargetFramework)' == 'uap10.0' ">
    <DefineConstants>UAP;NETFX_CORE</DefineConstants>
  </PropertyGroup>
```

Would a PR for this be feasible? Happy to provide, but want to discuss first.

**Comment by onovotny** [comment]
The implicit ifdef's are already provided.

They follow two patterns/conventions:

1. based on TFM: UAP_10_0_16299, NET47, etc. This is handled by the SDK itself.
2. Adding in the default/known ones for each TFM: https://github.com/onovotny/MSBuildSdkExtras/search?utf8=%E2%9C%93&q=DefineConstants&type=
2a. The Xamarin targets add the `__ANDROID__` symbols, etc.

Does that meet your needs or is there something else you were looking for?

**Comment by GeertvanHorrik** [comment]
I wasn't aware of 1. Do we want to include NET471 as well or is that also taken care of by the SDK itself? I had a question about targeting the UAP stuff. How do you know which SDK it targets, or is that only relevant for the actual apps and should we hope that the lib developers (in this case me) use the right dynamic feature detection?

**Comment by onovotny** [comment]
The SDK handles .NET Framework.

For the UWP, the SDK version is determined by the TFM. You should be using `uap10.0.16299` (or whatever the min build you're targeting is). That sets the Target Platform Min Version.

Just using `uap10.0` defaults to pre-RS3 behavior and it won't get the netstandard 2 support.

**Comment by GeertvanHorrik** [comment]
```
Just using uap10.0 defaults to pre-RS3 behavior and it won't get the netstandard 2 support.
```

Excellent, because I have netstandard 2.0 *and* uap builds to be able to support Windows 10 Mobile.

I use the NET / NET47 to make it easier to differentiate platforms in my code, but it looks like most of this is already included. If you want the NET / NET47, let me know by re-opening this ticket.

Thanks!

**Comment by onovotny** [comment]
@GeertvanHorrik you can multitarget `uap10.0` and `uap10.0.16299` as well

**Comment by GeertvanHorrik** [comment]
Wow, nice, thanks for the info!
