### ISSUE TITLE
Question: VS Tooling for WPF

### ISSUE THREAD

**Issue by commonsensesoftware** [onovotny/MSBuildSdkExtras#55]
### Synopsis
Getting WPF builds to work with the Common Project System is relatively straight forward. You've added a bunch of great tooling for the gaps.

Do you have any idea how to get Visual Studio to recognize the WPF tooling when CPS is used? I've tried everything I can think of, but I just can't make it work.

#### Attempt 1
To the best of my knowledge, this was determined by:

```xml
<ProjectTypeGuids>
  {FAE04EC0-301F-11D3-BF4B-00C04F79EFBC};
  {60DC8134-EBA5-43B8-BCC9-BB4BC16C2548}
</ProjectTypeGuids>
```

Which equates to `Visual C# | WPF`. This has always been the hook for Visual Studio tooling because there's been no other way to help tooling purely by convention in these scenarios (as it's more than just programming language). This value has no bearing on the build. I've tried many combinations, but Visual Studio will not honor the value.

#### Attempt 2
I've tried setting this directly in Solution (\*.sln) file (yuck - I know) like so:

```
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC};{60DC8134-EBA5-43B8-BCC9-BB4BC16C2548}") =
"WpfApp1", "WpfApp1\WpfApp1.csproj", "{316B4CDA-1A37-46BB-B417-CDA701B04AA7}"
EndProject
```
But that doesn't work either.

I started to suspect that perhaps there is branching logic in the VSPackage loader that chooses a different package if `Sdk="Microsoft.NET.Sdk"` is present. I was able to debunk that theory though by creating a new, standard WPF application and adding `Sdk="Microsoft.NET.Sdk"` to it.

#### Attempt 3
I also remembered that Visual Studio has a concept of _services_ that can be added to a project. I've seen it add the following to old test projects for 3rd party test frameworks as:

```xml
 <ItemGroup>
   <Service Include="{82a7f48d-3b50-4b1e-b82e-3ada8210c358}" />
 </ItemGroup>
```
I was hoping that might be another place to try adding the project type GUID:

```xml
 <ItemGroup>
   <Service Include="{60DC8134-EBA5-43B8-BCC9-BB4BC16C2548}" />
 </ItemGroup>
```
No dice.

### Final Thoughts
I also tried several combinations of deleting the `.vs` folder too. It didn't seem to make a difference. I think most can live without the context menu (e.g. `Add Window...`), but the **Add File Dialog** excludes all WPF content too. While it's possible to manually work around it, it's quite painful. Any thoughts, suggestions, or other experiences you can share are much appreciated.

I'm sure there many other customers wanting to make this work. If you know which Microsoft repo owns this tooling, I'm happy to also bark up their tree. Thanks.

**Comment by wjk** [comment]
@commonsensesoftware You might want to raise this at the [dotnet/project-system repo](https://github.com/dotnet/project-system).

**Comment by commonsensesoftware** [comment]
They are already aware of it and it looks like things will be formally addressed in .NET Core 3.0. As expected, the support was only a matter of time. As this repo contains many extensions and other missing functionality from MSBuild, I was just wondering if anyone else had a solution for this now. Seems like not, which is fine.
