### ISSUE TITLE
dotnet pack uniquely fails with PCL profile

### ISSUE THREAD

**Issue by AArnott** [onovotny/MSBuildSdkExtras#6]
When I use this setting, I get a build error:
```xml
    <TargetFrameworks>netstandard1.0;net45;portable-net45+win8+wp8+wpa81</TargetFrameworks>
```

`msbuild /t:pack` succeeds, but `dotnet pack` fails with:

> C:\Users\andarno\.nuget\packages\msbuild.sdk.extras\1.0.0-rc4.23\build\netstandard1.0\MSbuildSdkExtras.Common.targets(117,5): error : The specified TFM 'portable-net45+win8+wp8+wpa81' is not valid. Check that it's a valid combination: http://portablelibraryprofiles.apps.stephencleary.com/ [C:\git\validation\src\Microsoft.VisualStudio.Validation\Microsoft.VisualStudio.Validation.csproj]

**Comment by onovotny** [comment]
Weird, I'll take a look, but I'm not modifying the TFM anywhere. Only detecting the profile and framework versions based on contains searches of the portable strings. Not at all sure what would be causing something to pack to a diff directory.

For your other workaround, I'm happy to include it here. Can you submit a PR? Then this package can help be the fixes ppl need when using the SDK builds until the product has it directly....

**Comment by onovotny** [comment]
That comment was for your other issue. I'm not shew how to even debug this one given no debugging for msbuild.

**Comment by onovotny** [comment]
Just noticed the original issue changed to this.... I'll try to loop in ppl, but as desktop msbuild does work, at least it's not a blocker

**Comment by AArnott** [comment]
Ya, that initial issue was just me not running package restore between msbuild changes and running build. So I scratched it and replaced with this when I realized this was the only remaining problem. Sorry for the confusion.

**Comment by onovotny** [comment]
I'm not even sure dotnet.exe would work for a PCL because it's not going to have the MSBuildExtensionsPath with the Portable targets in it. Basically, you need the stuff in here: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Microsoft\Portable`, which doesn't ship with the dotnet.exe sdk AFAIK.

**Comment by AArnott** [comment]
ah, interesting point. Feel free to close when you're confident.
