### ISSUE TITLE
dotnet sdk import issues

### ISSUE THREAD

**Issue by obylium** [onovotny/MSBuildSdkExtras#64]
Hi @onovotny. First I'd like to thank you for putting this together, this has helped me tremendously so far.

I am in the middle of converting a solution of 4 projects to use the new csproj format using the .NET SDK. One of the requirements of this project is also to convert to using dotnet for all build commands. I have to make sure I get this to build in two different environments: using VS 2017 locally, for debugging, and using the dotnet sdk on the build server. This one WPF project is giving me significant pains. It currently builds in VS 2017 just fine, but when I am running the command `dotnet build --verbosity normal /p:Configuration=Release` I am getting the message:  `C:\Program Files\dotnet\sdk\2.1.105\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets(41,3): error MSB4019: The imported project "C:\Program Files\dotnet\sdk\2.1.105\15.0\Bin\Microsoft.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. [*.csproj]`

This is an example of my .csproj with some unnecessary stuff removed for the sake of anonymity (marked with a @@).

```XML
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <TargetFramework>net45</TargetFramework>
    <!--<RuntimeIdentifier>win7-x64</RuntimeIdentifier>-->
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <DocumentationFile>bin\$(Configuration)\@@.xml</DocumentationFile>
    <OutputPath>bin\$(Configuration)</OutputPath>
    <StartupObject>@@.App</StartupObject>
    <ApplicationIcon>Resources\@@.ico</ApplicationIcon>
    <OutputType>WinExe</OutputType>
    <LanguageTargets>$(MSBuildToolsPath)\Microsoft.CSharp.targets</LanguageTargets>
    <!--<CSharpTargets>$(MSBuildToolsPath)\Microsoft.CSharp.targets</CSharpTargets>-->
    <!--<CSharpTargets Condition="'$(CSharpTargets)' == ''">$(MSBuildToolsPath)\Microsoft.CSharp.targets</CSharpTargets>-->
  </PropertyGroup>
  <!-- Workaround for lack of XAML support using new project format. -->
  <Import Project="$(MSBuildSDKExtrasTargets)" Condition="Exists('$(MSBuildSDKExtrasTargets)')" />
  <!--<Import Project="$(CSharpTargets)" />-->
  <!--<Import Project="$(MSBuildBinPath)\Microsoft.CSharp.targets" />-->
  <!--<Import Project="$(BaseIntermediateOuputPath)$(OriginalProjectName).*.props" Condition=" '$(MSBuildProjectName)' != '$(OriginalProjectName)' and '$(ImportProjectExtensionProps)' != 'false' and exists('$(BaseIntermediateOuputPath)')" />-->
  <ItemGroup>
    <PackageReference Include="FontAwesome.WPF" Version="4.5.0.8" />
    <PackageReference Include="MSBuild.Sdk.Extras" Version="1.2.2" PrivateAssets="all" />
    <ProjectReference Include="..\@@.csproj" />
    <ProjectReference Include="..\@@.csproj" />
    <ProjectReference Include="..\@@.csproj" />
    <Reference Include="System" />
    <Reference Include="System.Configuration" />
    <Reference Include="System.Data" />
    <Reference Include="System.IO.Compression" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Xml" />
    <Reference Include="System.Core" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="System.Xaml" />
    <Reference Include="WindowsBase" />
    <Reference Include="PresentationCore" />
    <Reference Include="PresentationFramework" />
  </ItemGroup>
  <!--<Import Project="$(BaseIntermediateOuputPath)$(OriginalProjectName).*.targets" Condition=" '$(MSBuildProjectName)' != '$(OriginalProjectName)' and '$(ImportProjectExtensionProps)' == 'true' and exists('$(BaseIntermediateOuputPath)')" />-->
  <ItemGroup>
    <Resource Include="Resources\*.png;Resources\*.ico" />
    <EmbeddedResource Include="Resources\*.dll" />
  </ItemGroup>
</Project>
```

Now I can't confirm this to be a result of your package, as it might be a hidden error otherwise. I can comment out the MSBuildSDKExtrasTargets Import but I get stuck with xaml compilation errors which your package seems to help. I also no longer get the error when commented though so that leads me to believe something is creating a bad import from somewhere.

I'm slowly pulling my hair out with this. Do you have any ideas?

**Comment by GeertvanHorrik** [comment]
@obylium I believe this requires full msbuild in order to compile. See https://github.com/GeertvanHorrik/MultiTargetingProject for a fully-functioning cakebuild script that you could use to build your stuff via the command line.

**Comment by onovotny** [comment]
@GeertvanHorrik is correct, you must use `msbuild` for building these targets since `dotnet build` does not include all of the targets and tasks needed for these.
