### ISSUE TITLE
SDK-style import is lacking

### ISSUE THREAD

**Issue by AArnott** [onovotny/MSBuildSdkExtras#65]
I'm working on a project that I just installed the MSBuild.Sdk.Extras/1.4.0 using the SDK attribute. But now I need to define a property _after_ the .targets are imported. I can do this with Microsoft.NET.Sdk by removing the Sdk attribute and using Import/@Sdk instead. But when I try that with MSBuild.Sdk.Extras, it fails to find the SDK.

I can make this work using the old style for importing your .targets. But since you're deprecating that, I wanted to find out if you had a solution to this problem with the new style.

**Comment by onovotny** [comment]
I can add placeholder variables for imports that if set would be used. Aside from after the main targets, what other points do you think would be useful?

**Comment by AArnott** [comment]
I just want to set properties (such as CoreCompileDependsOn) that are (sadly) unconditionally cleared and set in the microsoft .targets.

I'm curious why msbuild's nuget sourcing of sdk's is limited to Project/@Sdk rather than working for Import/@Sdk as well. Any idea why they limited that?

**Comment by Nirmal4G** [comment]
@AndyGerlicher Please take a look at this, Is this a known issue?

**Comment by Nirmal4G** [comment]
after the SDK targets or the Microsoft.*.targets or the NetSdk targets?

**Comment by AArnott** [comment]
Thanks, @AndyGerlicher. Yes, I had tried to make the syntax-sugar equivalent change and it had failed. But as you guessed, I hadn't split the version out into its own attribute. Thanks!
