### ISSUE TITLE
Build error with xamarin android or ios app referencing a multi-targeted library (The target "GetBuiltProjectOutputRecursive" does not exist in the project)

### ISSUE THREAD

**Issue by tranb3r** [onovotny/MSBuildSdkExtras#75]
I've managed to build a multi-targeted lib for netstandard/android/ios, however when referencing this library from an android or ios app, the build of the app fails with this error:
error MSB4057: The target "GetBuiltProjectOutputRecursive" does not exist in the project.

How to reproduce the error (for android):
- Create a new solution containing a blank Android app and a netstandard library
- Reference the netstandard library from the android app => app build ok
- In the netstandard library csproj, change the tfm into MonoAndroid81 (using the MSBuild.Sdk.Extras/1.5.4 sdk) => app build ok
- In the library csproj, switch to multitargeting (rename TargetFramework into TargetFrameworks, but do not add other tfm than MonoAndroid81) => app build fails

Thoughts ?

**Comment by onovotny** [comment]
What version of VS are you using?

**Comment by tranb3r** [comment]
VS 2017 15.6.7
Same error with VS 2017 15.7.0 Preview 5

**Comment by onovotny** [comment]
I'll try again with 15.7.2, but it worked for me without issue on 15.8 preview 1.

**Comment by onovotny** [comment]
Also works for me in 15.7.2.

**Comment by tranb3r** [comment]
Upgrading VS2017 is not an option for me right now.
I'll do a test with 15.7.3 when it's available.

**Comment by tranb3r** [comment]
I've managed to do a test with 15.7.2. Strangely enough, I still had the same issue. But using a clean vm, no issue like you said.
So I've spent the whole day reinstalling my dev envrionment from scratch. And now it works ! So frustrating...
Anyway, thanks for your help!
