### ISSUE TITLE
Xaml file with ResourceDictionary does not get added on Pack

### ISSUE THREAD

**Issue by MSiccDev** [onovotny/MSBuildSdkExtras#77]
I want to add a style in my NuGet package for using it in a custom renderer for UWP. I created a Themes folder, added Generic.xaml, but I am not able to get it into the NuGet package. 

I am using multi targeting in this library, in a similar way Xamarin.Essentials does. The package structure shows a .pri file besides the dll, but the themes folder never shows up.

What am I missing?

**Comment by Nirmal4G** [comment]
Use it like this:

```xml
<ItemGroup>
    <Resource Include="Themes\Generic.xaml" Pack="true" PackagePath="uap10.0\Themes\"/>
</ItemGroup>
```

**Comment by onovotny** [comment]
You need to set/add `<GenerateLibraryLayout>true</GenerateLibraryLayout>`. The files will get included automatically then.

**Comment by Nirmal4G** [comment]
I forgot about that.

**Comment by MSiccDev** [comment]
Problem is that I already set `GenerateLibraryLayout ` to true, but the xaml file was not added. Maybe this is a problem with the Multi targeting setup I have for Xamarin Forms. :\

**Comment by Nirmal4G** [comment]
Will look into it.

**Comment by MSiccDev** [comment]
So trying to get this working, I added `<IncludeContentInPack>true</IncludeContentInPack>` and in the UWP condition `<Content Include="**\*.uwp.xaml" Pack="true" PackagePath="**\*"></Content>` 
 

tbh, this seems very hacky for me...

**Comment by Nirmal4G** [comment]
> Also, the Resource trick did not really work...

The `Resource` and other build items work only when both `IncludeContentInPack` property and `Pack` metadata (on that Item type) is set to true!

You don't need a separate Content item definition to get it working, i.e. use the same trick I mentioned and just add `<IncludeContentInPack>true</IncludeContentInPack>`. Any Item type having `Pack` metadata is included automatically.

**Comment by Nirmal4G** [comment]
Here's the target that enables this:

https://github.com/NuGet/NuGet.Client/blob/10b5c2128351c32f2a2ee09e457fa452082b2103/src/NuGet.Core/NuGet.Build.Tasks.Pack/NuGet.Build.Tasks.Pack.targets#L457-L506

**Comment by MSiccDev** [comment]
will try that, thanks
