### ISSUE TITLE
Xamarin.Mac20 intellisense support

### ISSUE THREAD

**Issue by tofutim** [onovotny/MSBuildSdkExtras#8]
I'm so glad I discovered this. I was getting really confused why Xamarin.iOS10 and Xamarin.Mac20 were not working in my VS2017-style csproj. Now that it works, how do I "using Xamarin.Mac" in the library?

This is what I currently have in my csproj:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>Xamarin.Mac20</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MSBuild.Sdk.Extras" Version="1.0.2" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Class1.cs" />
  </ItemGroup>
  
  <ItemGroup Condition=" '$(TargetFramework)' == 'Xamarin.Mac20' ">
    <Compile Include="Class1.cs" />
  </ItemGroup>
  
  <Import Project="$(MSBuildSDKExtrasTargets)" Condition="Exists('$(MSBuildSDKExtrasTargets)')" />

</Project>
```

**Comment by tofutim** [comment]
Actually, I just realized what I want is "Foundation" not "Xamarin.Mac" and it does work, except for the intellisense.

**Comment by onovotny** [comment]
I'm not sure I understand...why are you removing and then re-including class1?

If you're trying to conditionally include files per platform, you may need to use a `None Include` to ensure the solution explorer sees them. Long as they're included in at least one platform, IntelliSense should work.

You can see a fairly complex example here: https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/blob/dev/src/Microsoft.Identity.Client/Microsoft.Identity.Client.csproj#L48-L53

**Comment by tofutim** [comment]
Hi, turned out I did not need to remove and re-include if I am only targeting Xamarin.Mac20.  I was following an example which had None for *.cs and then conditionally re-added. I was about to say that I still see squiggles, but after restarting the solution to screencap the problem, I now see no problem! Fabulous.
