### ISSUE TITLE
error MSB4057: The target "_GetRestoreSettingsPerFramework" does not exist in the project.

### ISSUE THREAD

**Issue by AArnott** [onovotny/MSBuildSdkExtras#85]
After [updating to the latest MSBuild.Sdk.Extras](https://github.com/Microsoft/vs-validation/commit/6e01a620847f2a09f905ebd9e042d77db296de5a), [`dotnet restore` fails](https://ci.appveyor.com/project/AArnott/vs-validation/build/119) with:

> error MSB4057: The target "_GetRestoreSettingsPerFramework" does not exist in the project.

`msbuild /restore` still works, however.

**Comment by onovotny** [comment]
`dotnet`-based commands won't work with the extras...they'll always need `msbuild`. Is that a blocker?

**Comment by onovotny** [comment]
I don't think it's an intentional change, but it's not a configuration that's tested. The main reason is that all of the tasks brought in by the targets pointed to are based on .NET Framework and don't have .NET Core variants (today). Even `net` is bringing the full .NET Framework targets, which is how we can support WPF/WCF, etc.

**Comment by onovotny** [comment]
I'd certainly take a PR that fixes it for restore if there's an easy solution.

**Comment by AArnott** [comment]
Apparently it's not just restore. If I restore in another way, then use `dotnet build --no-restore` it fails with:

> error MSB4057: The target "Build" does not exist in the project.

I don't think I'll take time to look for a way to fix this right now. Maybe sometime if I have time and can't easily enough drop use of `dotnet.exe`.

**Comment by AArnott** [comment]
Ah, that's good. :)

**Comment by onovotny** [comment]
Here's how I do it for Rx.NET, with code coverage now from the latest SDK's:
https://github.com/dotnet/reactive/blob/master/.vsts.rx-shared.yml

I need one workaround since embedded pdb's aren't yet supported by code coverage, so I have to build again for it :/

**Comment by chucklu** [comment]
Encounter the same error information when build Newtonsoft.Json project, the solution is to install portable library
https://github.com/JamesNK/Newtonsoft.Json/issues/2057#issuecomment-493294589

**Comment by moljac** [comment]
also Guava Xamarin.Android builds on windows from XamarinComponents repo
