### ISSUE TITLE
CleanAllFiles task error in VS 15.8 preview 3

### ISSUE THREAD

**Issue by nickrandolph** [onovotny/MSBuildSdkExtras#89]
Repro Steps:
- Use VS 15.8 preview 3
- Grab source code from develop branch of Mvvmcross (https://github.com/MvvmCross/MvvmCross)
- Delete any existing obj/bin folders
- Open Mvvmcross.sln in VS
- Force Rebuild on MvvmCross project (this worked prior to preview 3 and we have CI on the project to ensure develop branch builds with each PR)

Error:
1>C:\Program Files (x86)\Microsoft Visual Studio\Preview\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(5012,7): error MSB4057: The target "_SdkBeforeClean
1>C:\Program Files (x86)\Microsoft Visual Studio\Preview\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(5012,7): error MSB4057:       
1>C:\Program Files (x86)\Microsoft Visual Studio\Preview\Professional\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(5012,7): error MSB4057: 			_CleanAllFiles" does not exist in the project.

**Comment by onovotny** [comment]
I'm having trouble reproducing this on the command line with 1.5.4 or 1.6.20-preview.

I'm trying with the command line, with a clean repo, running 

`msbuild /restore /t:rebuild`
or 
`msbuild /t:clean`

Each time, I'm running `git clean -xdf` to ensure it's clean.

**Comment by nickrandolph** [comment]
Do you see the issue if you do a build within Visual Studio?

**Comment by onovotny** [comment]
Which version of the extras? both? I'm trying to repro with the command line as it's easier to troubleshoot from there. Can you repro from there?

**Comment by nickrandolph** [comment]
I'll give it a shot later today

**Comment by onovotny** [comment]
Few things-- 

Not sure if related, but:

1. Don't include `Tizen.NET` or the UWP metapackages anywhere. The extras does that already for you
2. MvvmCross.Platforms.Wpf.csproj is in the same folder as MvvmCross.csproj. I'm fairly certain the project system doesn't like that and you'll be stepping on the `project.assets.json` in the obj folder.

**Comment by nickrandolph** [comment]
Yeh I did notice (1) - if we remove these, will it break on old versions of VS?
(2) - we were aware of the potential for this and for Forms the WPF csproj is in a different folder for that reason. This was building prior to preview 3

**Comment by onovotny** [comment]
For 1. Define old versions of VS? The only thing that does is have impact on being a nuget dependency. Tizen and UWP do their own thing for this and it's doing the right thing :)

For Tizen, it's a dependency, for UWP it's not, and it's not supposed to be. The app adds the UWP meta package reference directly, that's how it's supposed to work.

For 2, it's not a theoretical issue. You'd need to override the IntermediateOutputPath, and OutputPath and do it correctly, etc.


-- 

Getting back to the issue you're seeing, that `_SdkBeforeClean` was added by the .NET Core 2.1.300 SDK. The timing of 15.7.4 and 15.8 preview 3 could be conincidental. One of those could have included the SDK.

You can see where it was added here:
https://github.com/dotnet/sdk/commit/d0dcdae7cc36fe2e94a544087fe828ea7927f05b

That said, still need a minimal repro to see what's going on. As you can see, the override and the target are both defined in that single targets file, so I'm not sure how you'd get to a situation where the target could be missing.

**Comment by nickrandolph** [comment]
So I don't have 15.7 (any build) installed, only 15.8 preview 3. Wonder if that's the issue. How does VS know which path to look for to determine location of the Microsoft.NET.Sdk.targets - I want to see if the version I have installed has the _sdkbeforeclean task.

**Comment by nickrandolph** [comment]
I don't know whether it's related but I'm also seeing issues building the UWP sample projects we have in the mvvmcross solution, namely Playground.Uwp and Playground.Forms.Uwp. Both complain with the error:

8>C:\Program Files (x86)\Microsoft Visual Studio\Preview\Professional\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.targets(354,5): error : One of your dependencies requires the .NET Framework, but the .NET Framework could not be found in the NuGet packages installed in this project.  Please install the appropriate .NET Framework packages required by your dependency.

**Comment by nickrandolph** [comment]
As a follow up on the earlier points. After running git clean -xdf if I run:
_msbuild /t:clean_
This works fine - no errors.

If I run:
_msbuild /restore /t:rebuild_
I don't see the _SdkBeforeClean error but I do see the UWP error I mentioned in my previous comment:

"C:\Source\MvvmCross\MvvmCross.sln" (rebuild target) (1:2) ->
"C:\Source\MvvmCross\Projects\Playground\Playground.Uwp\Playground.Uwp.csproj" (Rebuild target) (54
:6) ->
(InjectNetCoreFrameworkBlockIfLockFileExists target) ->
  C:\Program Files (x86)\Microsoft Visual Studio\Preview\Professional\MSBuild\Microsoft\NuGet\15.0\Microsoft.NuGet.targ
ets(354,5): error : One of your dependencies requires the .NET Framework, but the .NET Framework could not be found in
the NuGet packages installed in this project.  Please install the appropriate .NET Framework packages required by your
dependency. [C:\Source\MvvmCross\Projects\Playground\Playground.Uwp\Playground.Uwp.csproj]

**Comment by nickrandolph** [comment]
I've done a bit of a tidy up of mvvmcross to try to remove build issues: https://github.com/nickrandolph/MvvmCross/tree/feature/sdkbuildissue
Unfortunately still seeing the UWP build error

**Comment by onovotny** [comment]
Looking at Playground.Uwp in that branch, I don't see a UWP meta-package reference there. Applications do need that still.

**Comment by nickrandolph** [comment]
ah ok, I was wondering about that. I'll add it back in and see how it goes

**Comment by nickrandolph** [comment]
Any luck repro'ing the _CleanAllFiles issues?

**Comment by nickrandolph** [comment]
FYI - I've just reverted back to 1.5.4 of the extras on this branch as I want to get the PR approved - https://github.com/nickrandolph/MvvmCross/tree/feature/sdkbuildissue

**Comment by onovotny** [comment]
Not yet, I need to get a command line repro. I don't see where it'd be coming from otherwise.

**Comment by nickrandolph** [comment]
Yeh I'm not sure of what'd be different between VS v's MBBuild. MSBuild works fine on both solution and individual projects.

**Comment by onovotny** [comment]
Closing as fixed by https://github.com/dotnet/sdk/issues/2387. The clean issue will be fixed in 15.8.

**Comment by nickrandolph** [comment]
Thanks for chasing this down!!

**Comment by nickrandolph** [comment]
For anyone else watching this issue, it doesn't seem to be fixed in 15.8 preview 4, so I'm guessing we need to wait for the next preview for this to be resolved.

**Comment by onovotny** [comment]
The PR implementing the fix indicates Preview 5: https://github.com/dotnet/sdk/pull/2388
