### ISSUE TITLE
MSBuild.Sdk.Extras does not seem to work in VS2017 for Mac

### ISSUE THREAD

**Issue by tofutim** [onovotny/MSBuildSdkExtras#9]
I just opened my solution in VS2017 for Mac. Project targeting Xamarin.Mac20 refuses to load. Any tips?

![image](https://user-images.githubusercontent.com/157766/26983239-f277d2fc-4cef-11e7-823b-4a054859208c.png)

Error is Load failed: Project does not support framework 'Xamarin.Mac, Version=v2.0'

**Comment by tofutim** [comment]
@mrward might also have some good ideas.

**Comment by mrward** [comment]
I suspect the load failed error is because currently VS for Mac is not allowing other target frameworks for sdk style projects. I should be able to fix that part.

**Comment by onovotny** [comment]
@mrward it would be good to get some validation that project using this package work correctly in VSfM. I don't see why they wouldn't since they load their language targets from the same place that the legacy projects do (same variables, etc).

**Comment by tofutim** [comment]
Let me know if I can help in any way. It would be a lifesaver for me since I just switched our libraries to SDK-style.

**Comment by onovotny** [comment]
@tofutim you could always use a PC, I hear Windows 10 has a great CLI now with bash ;)

/ducks and runs

**Comment by tofutim** [comment]
Lol. I do use a PC with Windows 10. The problem is that one of the final outputs referencing the libraries is a Cocoa App and it would be nice to be able to debug the app within VSfM. (I switched to SDK-style to avoid messing around with nuspecs...)

**Comment by tofutim** [comment]
@mrward Curious to see if you were able to fix the load failed error on your end. If ETA is not too far away we might leave the sln as is.

**Comment by tofutim** [comment]
@onovotny Just got word on some progress from @mrward 

Would it be possible to get a fallback VSfM directory integrated into MSBuild.Sdk.Extras?

> https://bugzilla.xamarin.com/show_bug.cgi?id=57307
> 
> --- Comment #12 from Matt Ward <matt.ward@xamarin.com> ---
> So the only thing I can do on the VSMac side is allow any target framework.
> However that by itself does not really help. The project will load but it will
> be using an odd target framework. With .NET Core SDK 2.0 installed the target
> framework is unknown and the TargetFrameworkMoniker is resolved to
> _,Version=1.0.
> 
> If you install MSBuild.Sdk.Extras the target framework is now recognised.
> However the build fails.
> 
> <Project Sdk="Microsoft.NET.Sdk">
> 
>   <PropertyGroup>
>     <TargetFramework>Xamarin.iOS10</TargetFramework>
>   </PropertyGroup>
> 
>         <ItemGroup>
>                 <PackageReference Include="MSBuild.Sdk.Extras" Version="1.0.0"
> PrivateAssets="all" />
>         </ItemGroup>
> 
>         <Import Project="$(MSBuildSDKExtrasTargets)"
> Condition="Exists('$(MSBuildSDKExtrasTargets)')" />
> </Project>
> 
> 
> (DisplayMissingLanguageTargetsError target) ->
> 
> ~/.nuget/packages/msbuild.sdk.extras/1.0.0/build/netstandard1.0/MSbuildSdkExtras.Common.targets(116,5):
> error : The specified language targets for Xamarin.iOS10 is missing. Ensure
> correct tooling is installed./r/nMissing File:
> /Library/Frameworks/Mono.framework/Versions/5.4.0/lib/mono/xbuild/Xamarin/iOS/Xamarin.iOS.CSharp.targets
> [~/Projects/Tests/MyProject/MyProject.csproj]
> 
> The Xamarin.iOS.Csharp.targets is available from a different folder:
> 
> /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.CSharp.targets
> 
> A normal Xamarin.iOS project will have an Import of the form:
> 
> <Import
> Project="$(MSBuildExtensionsPath)\Xamarin\iOS\Xamarin.iOS.CSharp.targets" />
> 
> The MSBuildExtensionsPath has multiple values:
> 
> /Library/Frameworks/Mono.framework/Versions/5.4.0/lib/mono/xbuild:/Library/Frameworks/Mono.framework/External/xbuild/
> 
> So more work elsewhere on the Xamarin side or a change in the
> MSBuild.Sdk.Extras NuGet package is required.
> 
> So I believe I can create a separate addin to allow VSMac 7.0 and above to load
> a .NET Core project that targets Xamarin.iOS, without changing VSMac itself,
> but nothing else will work. However whether a similar change gets added to
> VSMac directly is another question since the project right now will be
> unsupported and not work.

**Comment by onovotny** [comment]
This is now fixed with the latest beta on NuGet. Details on what you need here: https://oren.codes/2017/08/29/use-all-tfms-with-sdk-style-projects-in-visual-studio-for-mac/

**Comment by alexfmpe** [comment]
Following the directions in the blog allowed me to convert a xamarin android 'library' .csproj  to sdk-style and have it working in Mac OS X - both VSfM and CLI (this unblocked adoption on multi-platform projects).
However, I've been unsuccessful at doing the same for the xamarin android 'app' .csproj.
Is it even possible for sdk-style .csproj to take the 'app' role in xamarin android/iOS? (at least I can't convince VSfM or VS).
I'd like to know if this is just not possible in msbuild-land and/or it's a considered scenario for MSBuildSdkExtras.

**Comment by onovotny** [comment]
It's not currently possible to have the app projects as SDK style since they need specific support for deployment and debugging.

They can use PackageReference though.

**Comment by chucker** [comment]
>It's not currently possible to have the app projects as SDK style since they need specific support for deployment and debugging.

Is that still current? (If so, is that something that needs fixing on the IDE side?)

I got surprisingly far with a Xamarin.Mac20 + VS4Mac project — an app bundle does get generated, and I _can_ manually launch that. However, debugging does not work; apparently, Mono doesn't know where to find the references (even though it does copy them to the app bundle).
