### ISSUE TITLE
ExtrasUserControlDesignerService?

### ISSUE THREAD

**Issue by wjk** [onovotny/MSBuildSdkExtras#90]
Just a quick question here: What is the purpose of the `ExtrasUserControlDesignerService` property? From the name and usage I think it would enable WinForms designer support in an SDK-style csproj. If true, this would be great news. Unfortunately, it doesn't seem to do anything on my computer (VS 15.7.4). Is this feature only supported in the 15.8 beta? I can't find anything about it in the VS beta release notes. Thanks!

**Comment by onovotny** [comment]
@Nirmal4G Added that in, not completely sure. @Nirmal4G can you comment?
