### ISSUE TITLE
Warnings on <Sdk /> style import

### ISSUE THREAD

**Issue by andrew-boyarshin** [onovotny/MSBuildSdkExtras#97]
MSBuild warnings:
```
C:\Users\<user>\.nuget\packages\msbuild.sdk.extras\1.6.41\Sdk\Sdk.props(11,3): warning MSB4011: "C:\Program Files\dotnet\sdk\2.1.400-preview-009063\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.props" cannot be imported again. It was already imported at "<project path>\project.csproj". This is most likely a build authoring error. This subsequent import will be ignored.
C:\Users\<user>\.nuget\packages\msbuild.sdk.extras\1.6.41\Sdk\Sdk.targets(15,3): warning MSB4011: "C:\Program Files\dotnet\sdk\2.1.400-preview-009063\Sdks\Microsoft.NET.Sdk\Sdk\Sdk.targets" cannot be imported again. It was already imported at "<project path>\project.csproj". This is most likely a build authoring error. This subsequent import will be ignored.
```

Sample project:
```xml
<Project Sdk="Microsoft.NET.Sdk">
  <Sdk Name="MSBuild.Sdk.Extras" />
  <Sdk Name="Microsoft.Build.CentralPackageVersions" />
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <ExtrasEnableWpfProjectSetup>true</ExtrasEnableWpfProjectSetup>
  </PropertyGroup>
</Project>
```

I believe some checks are needed in _Sdk\Sdk.props_ and _Sdk\Sdk.targets_ not to import _Microsoft.NET.Sdk_ if already imported, since ```<Sdk />``` imports are valid scenario too (I believe they are much more maintainable than ```<Project Sdk="" />```).

**Comment by onovotny** [comment]
Hi,

The extras should be in place of the Microsoft.NET.Sdk in the Project element. It will include that in the correct locations.

**Comment by onovotny** [comment]
That cannot work though due to ordering requirements. The extras needs things both before and after the main SDK targets to work. Thats why it does the import.

**Comment by andrew-boyarshin** [comment]
I see. Makes sense. Still, that's unfortunate limitation. Linking [msbuild issue](https://github.com/Microsoft/msbuild/issues/2803#issuecomment-362016864) for reference. Feel free to close if you believe this is not an issue then.
